import '../marketing.css';

export default function PricingPage(){
  return <main className="marketing">
    <nav className="siteNav"><a className="siteBrand" href="/"><div className="siteLogo">◎</div><div><b>emissa.tech</b><small>Supplier Compliance Infrastructure</small></div></a><div className="navLinks"><a href="/solutions/supplier-compliance-infrastructure">Solutions</a><a href="/demo">Demo</a><a className="button" href="/login">Log in</a></div></nav>
    <section className="section" style={{paddingTop:90}}><div className="sectionHead"><p className="eyebrow">Founding customer pricing</p><h2>Premium supplier compliance infrastructure. One monthly subscription.</h2><p className="heroCopy">The first 50 companies receive the full Emissa suite plus a two-week implementation at the founding rate. Scope 3 is included as the core supplier-data foundation, not sold as a separate add-on.</p></div><div className="pricingWrap"><article className="priceCard"><h3>Full supplier compliance suite</h3><ul><li>Supplier compliance operating layer</li><li>Scope 1, 2 and 3 carbon accounting</li><li>Supplier network and buyer requests</li><li>EPR and packaging compliance</li><li>CBAM workflows</li><li>Climate risk</li><li>LCA and product footprints</li><li>Certificates and deadline tracking</li><li>Integrations and multi-facility rollups</li><li>Due-diligence data rooms</li><li>Admin analytics and CRM</li><li>Future Emissa modules</li></ul></article><article className="priceCard featured"><p className="eyebrow">Founding subscription</p><div className="price">$3,500</div><h3>per month</h3><p className="heroCopy">Two-week onboarding included. Founding rate limited to the first 50 customers. Planned standard full-suite price after the founding cohort: $4,500/month.</p><a className="button primary" href="/demo">Start with a product demo</a><p className="muted" style={{marginTop:14}}>48 of 50 founding spots currently available.</p></article></div></section>
    <section className="section"><div className="sectionHead"><p className="eyebrow">Two-week implementation</p><h2>Get to a usable supplier compliance workflow quickly.</h2></div><div className="grid3"><article className="demoCard"><h3>Days 1-3</h3><p>Company profile, buyer and regulatory requirements, users and data-source mapping.</p></article><article className="demoCard"><h3>Days 4-8</h3><p>Connect priority systems, import supplier evidence and configure the first Scope 3 or compliance workflows.</p></article><article className="demoCard"><h3>Days 9-14</h3><p>Validate outputs, train the team and move the dashboard into active use.</p></article></div></section>
  </main>
}
