import '../marketing.css';

export default function PricingPage(){
  return <main className="marketing">
    <nav className="siteNav"><a className="siteBrand" href="/"><div className="siteLogo">◎</div><div><b>emissa.tech</b><small>Compliance OS</small></div></a><div className="navLinks"><a href="/demo">Demo</a><a className="button" href="/login">Log in</a></div></nav>
    <section className="section" style={{paddingTop:90}}><div className="sectionHead"><p className="eyebrow">Founding customer pricing</p><h2>One platform. Every module included.</h2><p className="heroCopy">The first 50 customers receive full-suite access plus a two-week implementation at the founding rate.</p></div><div className="pricingWrap"><article className="priceCard"><h3>Full suite</h3><ul><li>Scope 1, 2 and 3 carbon accounting</li><li>Supplier network and buyer requests</li><li>EPR and packaging compliance</li><li>CBAM workflows</li><li>Climate risk</li><li>LCA and product footprints</li><li>Certificates and deadline tracking</li><li>Integrations and multi-facility rollups</li><li>Due-diligence data rooms</li><li>Admin analytics and CRM</li><li>Future Emissa modules</li></ul></article><article className="priceCard featured"><p className="eyebrow">Legacy subscription</p><div className="price">$2,500</div><h3>per month</h3><p className="heroCopy">No setup fee. Two-week onboarding included. Founding rate limited to the first 50 customers.</p><a className="button primary" href="https://buy.stripe.com/28EdR96XCcKu5LTd0Kb7y00">Secure founding pricing</a><p className="muted" style={{marginTop:14}}>48 of 50 founding spots currently available.</p></article></div></section>
    <section className="section"><div className="sectionHead"><p className="eyebrow">Two-week implementation</p><h2>Get to a usable compliance workflow quickly.</h2></div><div className="grid3"><article className="demoCard"><h3>Days 1-3</h3><p>Company profile, requirements, users and data-source mapping.</p></article><article className="demoCard"><h3>Days 4-8</h3><p>Connect priority systems, import evidence and configure the first workflows.</p></article><article className="demoCard"><h3>Days 9-14</h3><p>Validate outputs, train the team and move the dashboard into active use.</p></article></div></section>
  </main>
}
