const pages=[...document.querySelectorAll('.page')];const nav=[...document.querySelectorAll('.nav-item')];const title=document.getElementById('pageTitle');const titles={overview:'Executive Command Center',core:'Emissa Core',network:'Supplier Network',epr:'EPR Compliance',cbam:'CBAM Workspace',risk:'Climate Risk Intelligence',lca:'LCA Studio',regulations:'Regulatory Map',reports:'Report Center',settings:'Admin Settings'};const toast=document.getElementById('toast');const showToast=m=>{toast.textContent=m;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)};function go(id){pages.forEach(p=>p.classList.toggle('active',p.id===id));nav.forEach(n=>n.classList.toggle('active',n.dataset.page===id));title.textContent=titles[id]||'Emissa';document.querySelector('.sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}nav.forEach(n=>n.onclick=()=>go(n.dataset.page));document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>go(b.dataset.jump));document.getElementById('openSidebar').onclick=()=>document.querySelector('.sidebar').classList.add('open');document.getElementById('closeSidebar').onclick=()=>document.querySelector('.sidebar').classList.remove('open');

function lineChart(canvasId,values,labels){const c=document.getElementById(canvasId);if(!c)return;const ctx=c.getContext('2d'),w=c.width=c.clientWidth*2,h=c.height=c.height*2;ctx.clearRect(0,0,w,h);ctx.lineWidth=4;ctx.strokeStyle='rgba(114,255,208,.18)';for(let i=0;i<5;i++){ctx.beginPath();ctx.moveTo(30,i*h/5+20);ctx.lineTo(w-20,i*h/5+20);ctx.stroke()}const max=Math.max(...values)*1.15;ctx.strokeStyle='#20e69b';ctx.lineWidth=7;ctx.beginPath();values.forEach((v,i)=>{const x=40+i*(w-80)/(values.length-1),y=h-40-(v/max)*(h-90);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#72ffd0';values.forEach((v,i)=>{const x=40+i*(w-80)/(values.length-1),y=h-40-(v/max)*(h-90);ctx.beginPath();ctx.arc(x,y,8,0,7);ctx.fill();ctx.font='24px Inter';ctx.fillText(labels[i],x-24,h-8);ctx.fillText('$'+v+'M',x-22,y-16)})}function donut(canvasId,values,labels){const c=document.getElementById(canvasId);if(!c)return;const ctx=c.getContext('2d'),w=c.width=c.clientWidth*2,h=c.height=c.height*2,cx=w/2,cy=h/2,r=Math.min(w,h)/3;let start=-Math.PI/2;const colors=['#20e69b','#72ffd0','#0a7652'];values.forEach((v,i)=>{const a=v/values.reduce((a,b)=>a+b,0)*Math.PI*2;ctx.beginPath();ctx.strokeStyle=colors[i];ctx.lineWidth=34;ctx.arc(cx,cy,r,start,start+a);ctx.stroke();start+=a});ctx.fillStyle='#f4fffb';ctx.font='900 36px Inter';ctx.textAlign='center';ctx.fillText('18.4K',cx,cy);ctx.fillStyle='#93a9a3';ctx.font='22px Inter';ctx.fillText('tCO2e',cx,cy+34);ctx.textAlign='left';labels.forEach((l,i)=>{ctx.fillStyle=colors[i];ctx.fillRect(30,30+i*38,18,18);ctx.fillStyle='#bfd1cb';ctx.font='22px Inter';ctx.fillText(l+' '+values[i]+'%',58,48+i*38)})}

lineChart('arrChart',[4.6,11.7,27.8,56.5,101],['Y1','Y2','Y3','Y4','Y5']);donut('scopeChart',[12,18,70],['Scope 1','Scope 2','Scope 3']);window.addEventListener('resize',()=>{lineChart('arrChart',[4.6,11.7,27.8,56.5,101],['Y1','Y2','Y3','Y4','Y5']);donut('scopeChart',[12,18,70],['Scope 1','Scope 2','Scope 3'])});

const coreLog=document.getElementById('coreLog');document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const text={connect:'QuickBooks connected. 18,420 transactions imported.',map:'Spend mapped to 15 GHG Protocol Scope 3 categories.',calculate:'Emissions calculated: 18,430 tCO2e with factor traceability.',verify:'Audit package verified and ready for Walmart, EcoVadis, or CDP.'};coreLog.innerHTML='<p>'+text[b.dataset.action]+'</p>';showToast(text[b.dataset.action])});

document.getElementById('simulateBtn').onclick=()=>{document.getElementById('obligationMetric').textContent='13';showToast('New Walmart supplier request added: Scope 3 package due in 7 days')};document.getElementById('generateBtn').onclick=()=>{addReport('Executive Emissions Report','Generated just now','Ready');go('reports');showToast('Report generated')};document.getElementById('sharePacket').onclick=()=>showToast('Verified ESG data packet shared with buyer portal');

document.getElementById('calcFees').onclick=()=>{const state=document.getElementById('stateSelect').value;document.getElementById('feeResult').innerHTML='<b>'+state+'</b><br>Estimated packaging obligation: $42,800. Materials flagged: PET, corrugate, flexible film. Filing package ready.';showToast('EPR fees calculated')};document.getElementById('buildCbam').onclick=()=>{const val=document.getElementById('shipmentInput').value||'250000',mat=document.getElementById('materialSelect').value;document.getElementById('cbamResult').innerHTML='<b>CBAM declaration created</b><br>'+mat+' shipment value $'+Number(val).toLocaleString()+'. Embedded carbon estimate: 184 tCO2e. Export docs ready.';showToast('CBAM declaration created')};document.querySelectorAll('[data-risk]').forEach(b=>b.onclick=()=>{const copy={flood:'Flood exposure elevated at 2 facilities. Recommended mitigation: supplier diversification and insurance review.',heat:'Heat stress risk moderate across southeast operations. 2030 productivity loss estimate: 3.1%.',energy:'Energy transition risk low. 68% of electricity spend can be shifted to lower-carbon contracts.',supplier:'Supplier disruption risk medium. 11 suppliers overlap with high-risk climate zones.'};document.getElementById('riskResult').innerHTML='<b>'+b.textContent+'</b><br>'+copy[b.dataset.risk];showToast('Risk model loaded')});document.getElementById('buildLca').onclick=()=>{const sku=document.getElementById('skuInput').value||'Premium Component A';document.getElementById('lcaResult').innerHTML='<b>'+sku+'</b><br>Cradle-to-gate footprint: 8.7 kgCO2e/unit. Hotspot: purchased materials at 71%. EPD draft ready.';showToast('Product footprint generated')};

const regionContent=document.getElementById('regionContent');const regionData={us:'<b>United States</b><br>CA SB 253, CA SB 261, SEC climate disclosure, and state EPR filings. 4 obligations active for this account.',eu:'<b>European Union</b><br>CBAM, CSRD, Digital Product Passport, and product-level lifecycle data requirements. 3 export risks detected.',buyers:'<b>Buyer mandates</b><br>Walmart Project Gigaton, Apple supplier disclosures, Costco packaging requests, and Target ESG questionnaires.'};function setRegion(r){regionContent.innerHTML=regionData[r];document.querySelectorAll('.map-tabs button').forEach(x=>x.classList.toggle('active',x.dataset.region===r))}document.querySelectorAll('[data-region]').forEach(b=>b.onclick=()=>setRegion(b.dataset.region));setRegion('us');

const reportList=document.getElementById('reportList');const reports=[['Walmart Project Gigaton Packet','Updated 2 hours ago','Ready'],['Scope 1/2/3 Audit Trail','Updated yesterday','Ready'],['EPR Packaging Summary','Draft','Needs review'],['CBAM Export Declaration','Draft','Needs shipment data']];function addReport(name,time,status){reports.unshift([name,time,status]);renderReports()}function renderReports(){reportList.innerHTML=reports.map(r=>'<div class="report-item"><div><b>'+r[0]+'</b><p>'+r[1]+'</p></div><button class="ghost" onclick="showToast(\''+r[0]+' opened\')">Open</button><span class="pill">'+r[2]+'</span></div>').join('')}renderReports();

document.getElementById('saveSettings').onclick=()=>{const c=document.getElementById('companyName').value;document.getElementById('settingsSaved').innerHTML='<b>Saved</b><br>Demo account set to '+c+'. Buyer deadlines and dashboard values refreshed.';showToast('Settings saved')};

const copilot=document.getElementById('copilot'),chat=document.getElementById('chat'),input=document.getElementById('chatInput');document.getElementById('openCopilot').onclick=()=>copilot.classList.add('open');document.getElementById('closeCopilot').onclick=()=>copilot.classList.remove('open');function sendChat(){const q=input.value.trim();if(!q)return;chat.innerHTML+='<p class="user">'+q+'</p>';let a='I found 3 compliance actions: finish Scope 3 verification, answer the Walmart packet, and review EPR packaging weights.';if(q.toLowerCase().includes('report'))a='I can generate Core, EPR, CBAM, LCA, or buyer-specific reports. I recommend the Walmart Project Gigaton packet first.';if(q.toLowerCase().includes('gap'))a='Top gaps: missing supplier activity data, incomplete packaging weights, and one EU shipment missing embedded-carbon factors.';if(q.toLowerCase().includes('buyer'))a='Buyer view is ready: 98% verified, 12 obligations, and a one-click data packet prepared for sharing.';setTimeout(()=>{chat.innerHTML+='<p class="ai">'+a+'</p>';chat.scrollTop=chat.scrollHeight},250);input.value=''}document.getElementById('sendChat').onclick=sendChat;input.addEventListener('keydown',e=>{if(e.key==='Enter')sendChat()});