const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const STRIPE_URL='https://buy.stripe.com/28EdR96XCcKu5LTd0Kb7y00';
const seed={
 emissions:[
  {id:crypto.randomUUID(),date:'2026-01-15',scope:'Scope 1',category:'Fleet fuel',source:'Fuel cards',amount:1240,status:'complete'},
  {id:crypto.randomUUID(),date:'2026-02-10',scope:'Scope 2',category:'Purchased electricity',source:'Utility bills',amount:2380,status:'complete'},
  {id:crypto.randomUUID(),date:'2026-03-01',scope:'Scope 3',category:'Purchased goods',source:'ERP spend',amount:6890,status:'pending'}],
 epr:[
  {id:crypto.randomUUID(),jurisdiction:'California',material:'Plastic',weight:18400,fee:42200,status:'pending'},
  {id:crypto.randomUUID(),jurisdiction:'Oregon',material:'Paper',weight:9200,fee:11600,status:'complete'}],
 cbam:[
  {id:crypto.randomUUID(),shipment:'EU-8852',product:'Steel component',origin:'USA',embedded:14.8,status:'blocked'},
  {id:crypto.randomUUID(),shipment:'EU-8914',product:'Aluminum housing',origin:'Mexico',embedded:7.2,status:'complete'}],
 risk:[
  {id:crypto.randomUUID(),asset:'Miami Distribution Center',hazard:'Hurricane',score:82,status:'pending'},
  {id:crypto.randomUUID(),asset:'Phoenix Supplier Plant',hazard:'Extreme heat',score:68,status:'pending'}],
 lca:[
  {id:crypto.randomUUID(),product:'Model A Packaging',stage:'Cradle-to-gate',footprint:12.4,status:'complete'},
  {id:crypto.randomUUID(),product:'Industrial Pump',stage:'Cradle-to-grave',footprint:86.9,status:'pending'}],
 obligations:[
  {id:crypto.randomUUID(),name:'Buyer emissions request',owner:'Sustainability',due:'2026-07-28',status:'pending'},
  {id:crypto.randomUUID(),name:'CBAM shipment packet',owner:'Trade Compliance',due:'2026-07-18',status:'blocked'},
  {id:crypto.randomUUID(),name:'Packaging data review',owner:'Operations',due:'2026-08-05',status:'complete'}]
};
const store={load(){const saved=localStorage.getItem('emissa-mvp');return saved?JSON.parse(saved):structuredClone(seed)},save(){localStorage.setItem('emissa-mvp',JSON.stringify(state))},reset(){localStorage.removeItem('emissa-mvp');state=structuredClone(seed);renderAll();toast('Demo data reset')}};
let state=store.load();
const modules={
 core:{title:'Emissa Core',subtitle:'Carbon accounting and buyer-ready GHG reporting.',features:['Connect ERP, accounting, utility, fleet and procurement data','Classify activity into Scope 1, 2 and 3 categories','Calculate tCO₂e and preserve source evidence','Export inventory and buyer response packages'],steps:['Connect','Classify','Calculate','Verify','Report'],dataset:'emissions'},
 epr:{title:'EPR Compliance',subtitle:'Packaging obligations, material tracking and fee estimates.',features:['Track rules by jurisdiction','Classify packaging by material and weight','Estimate producer responsibility fees','Prepare filing calendars and evidence'],steps:['Import','Classify','Map','Estimate','File'],dataset:'epr'},
 cbam:{title:'CBAM Reporting',subtitle:'Shipment-level embedded carbon and EU declaration readiness.',features:['Identify covered products','Collect facility and production evidence','Calculate embedded carbon','Build importer-ready declaration packets'],steps:['Shipment','Facility','Carbon','Validate','Declare'],dataset:'cbam'},
 risk:{title:'Climate Risk',subtitle:'Physical and transition risk intelligence.',features:['Map assets and suppliers','Screen hazards and transition risks','Score exposure','Produce board and disclosure summaries'],steps:['Locate','Screen','Model','Score','Disclose'],dataset:'risk'},
 lca:{title:'LCA Studio',subtitle:'Product carbon footprints and lifecycle models.',features:['Import bill of materials','Model manufacturing and logistics','Calculate product footprint','Compare design and supplier alternatives'],steps:['Materials','Manufacture','Transport','End of life','Publish'],dataset:'lca'},
 network:{title:'Emissa Network',subtitle:'Supplier and buyer ESG data exchange.',features:['Invite buyers and suppliers','Share verified ESG packets','Track data requests','Maintain reusable evidence'],steps:['Invite','Request','Validate','Share','Confirm'],dataset:'obligations'},
 reports:{title:'Reports Center',subtitle:'Generate executive and compliance outputs.',features:['GHG inventory','EcoVadis evidence package','CBAM packet','EPR summary and LCA report'],steps:['Select','Validate','Generate','Review','Export'],dataset:'obligations'}
};
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2000)}
function go(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id));$('#sidebar').classList.remove('open');$('#mask').classList.remove('show');scrollTo({top:0,behavior:'smooth'});if(modules[id])renderModule(id)}
function totalEmissions(){return state.emissions.reduce((a,b)=>a+Number(b.amount||0),0)}
function renderDashboard(){
 $('#totalEmissions').textContent=totalEmissions().toLocaleString();
 $('#openObligations').textContent=state.obligations.filter(x=>x.status!=='complete').length;
 $('#completedTasks').textContent=state.obligations.filter(x=>x.status==='complete').length;
 $('#legacyRemaining').textContent='48';
 const due=state.obligations.slice().sort((a,b)=>a.due.localeCompare(b.due)).slice(0,4);
 $('#notifications').innerHTML=due.map(x=>`<div class="item"><b>${x.name}</b><div class="muted">${x.owner} · due ${x.due}</div><span class="status ${x.status}">${x.status}</span></div>`).join('');
}
function columnsFor(ds){return {emissions:['date','scope','category','source','amount','status'],epr:['jurisdiction','material','weight','fee','status'],cbam:['shipment','product','origin','embedded','status'],risk:['asset','hazard','score','status'],lca:['product','stage','footprint','status'],obligations:['name','owner','due','status']}[ds]}
function renderTable(ds,filter=''){const rows=state[ds].filter(r=>JSON.stringify(r).toLowerCase().includes(filter.toLowerCase()));const cols=columnsFor(ds);return `<div class="tableWrap"><table class="table"><thead><tr>${cols.map(c=>`<th>${c}</th>`).join('')}<th>Actions</th></tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${c==='status'?`<span class="status ${r[c]}">${r[c]}</span>`:r[c]}</td>`).join('')}<td><button class="btn" data-edit="${ds}:${r.id}">Edit</button> <button class="btn danger" data-delete="${ds}:${r.id}">Delete</button></td></tr>`).join('')}</tbody></table></div>`}
function renderModule(id){const m=modules[id];const ds=m.dataset;$('#moduleHost').innerHTML=`<div class="glass moduleHero"><span class="tag">${m.title}</span><h1>${m.title}</h1><p class="muted">${m.subtitle}</p></div><div class="moduleLayout"><div class="glass panel"><h2>What it does</h2><div class="featureGrid">${m.features.map(x=>`<div class="feature">${x}</div>`).join('')}</div><h2>Workflow</h2><div class="workflow">${m.steps.map((x,i)=>`<div class="glass step"><b>${i+1}. ${x}</b><span class="muted">Demo workflow stage</span></div>`).join('')}</div></div><div class="glass panel"><h2>Actions</h2><button class="btn primary" data-add="${ds}" style="width:100%">Add ${m.title} Record</button><button class="btn" data-export="${ds}" style="width:100%;margin-top:10px">Export CSV</button><button class="btn" data-complete="${ds}" style="width:100%;margin-top:10px">Complete Pending Workflow</button><p class="muted">Data is stored in this browser for the MVP demo.</p></div></div><div class="glass panel" style="margin-top:16px"><div class="toolbar"><h2>Operational Data</h2><input id="moduleSearch" placeholder="Search records..."></div><div id="moduleTable">${renderTable(ds)}</div></div>`;
 $('#moduleSearch').oninput=e=>$('#moduleTable').innerHTML=renderTable(ds,e.target.value);
}
function fieldsFor(ds,r={}){const specs={emissions:[['date','date'],['scope','text'],['category','text'],['source','text'],['amount','number'],['status','select']],epr:[['jurisdiction','text'],['material','text'],['weight','number'],['fee','number'],['status','select']],cbam:[['shipment','text'],['product','text'],['origin','text'],['embedded','number'],['status','select']],risk:[['asset','text'],['hazard','text'],['score','number'],['status','select']],lca:[['product','text'],['stage','text'],['footprint','number'],['status','select']],obligations:[['name','text'],['owner','text'],['due','date'],['status','select']]}[ds];return specs.map(([name,type])=>type==='select'?`<label>${name}<select name="${name}"><option ${r[name]==='pending'?'selected':''}>pending</option><option ${r[name]==='complete'?'selected':''}>complete</option><option ${r[name]==='blocked'?'selected':''}>blocked</option></select></label>`:`<label>${name}<input name="${name}" type="${type}" value="${r[name]??''}" required></label>`).join('')}
function openForm(ds,id){const r=id?state[ds].find(x=>x.id===id):{};$('#modalBody').innerHTML=`<h2>${id?'Edit':'Add'} record</h2><form id="recordForm" class="form">${fieldsFor(ds,r)}<div class="formActions"><button class="btn primary" type="submit">Save</button><button class="btn" type="button" id="closeModal">Cancel</button></div></form>`;$('#modal').classList.add('open');$('#closeModal').onclick=()=>$('#modal').classList.remove('open');$('#recordForm').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));Object.keys(data).forEach(k=>{if(['amount','weight','fee','embedded','score','footprint'].includes(k))data[k]=Number(data[k])});if(id)Object.assign(r,data);else state[ds].push({id:crypto.randomUUID(),...data});store.save();$('#modal').classList.remove('open');renderAll();toast('Record saved')};}
function del(ds,id){state[ds]=state[ds].filter(x=>x.id!==id);store.save();renderAll();toast('Record deleted')}
function exportCSV(ds){const cols=columnsFor(ds);const csv=[cols.join(','),...state[ds].map(r=>cols.map(c=>`"${String(r[c]??'').replaceAll('"','""')}"`).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`emissa-${ds}.csv`;a.click();URL.revokeObjectURL(a.href);toast('CSV exported')}
function complete(ds){const item=state[ds].find(x=>x.status!=='complete');if(item){item.status='complete';store.save();renderAll();toast('Workflow completed')}else toast('No pending records')}
function renderAll(){renderDashboard();const active=$('.nav.active')?.dataset.view;if(active&&modules[active])renderModule(active)}
function searchAll(q){const results=[];Object.entries(state).forEach(([ds,rows])=>rows.forEach(r=>{if(JSON.stringify(r).toLowerCase().includes(q.toLowerCase()))results.push({ds,r})}));$('#searchResults').innerHTML=results.length?results.slice(0,20).map(x=>`<div class="item"><b>${x.ds}</b><div class="muted">${Object.values(x.r).filter(v=>typeof v!=='object').slice(1,5).join(' · ')}</div></div>`).join(''):'<p class="muted">No matches.</p>';}
$$('.nav,[data-view]').forEach(n=>n.onclick=()=>go(n.dataset.view));$('#openMenu').onclick=()=>{$('#sidebar').classList.add('open');$('#mask').classList.add('show')};$('#mask').onclick=()=>{$('#sidebar').classList.remove('open');$('#mask').classList.remove('show')};$('#globalSearch').oninput=e=>searchAll(e.target.value);$('#resetDemo').onclick=()=>store.reset();$('#stripeBtn').onclick=()=>window.open(STRIPE_URL,'_blank');document.body.addEventListener('click',e=>{const add=e.target.closest('[data-add]');const edit=e.target.closest('[data-edit]');const delBtn=e.target.closest('[data-delete]');const exp=e.target.closest('[data-export]');const comp=e.target.closest('[data-complete]');if(add)openForm(add.dataset.add);if(edit){const [ds,id]=edit.dataset.edit.split(':');openForm(ds,id)}if(delBtn){const [ds,id]=delBtn.dataset.delete.split(':');del(ds,id)}if(exp)exportCSV(exp.dataset.export);if(comp)complete(comp.dataset.complete)});renderAll();
