import type { SeoEntry } from './seoExpansionContent';

const pc=(title:string,problem:string,fields:string[],related:string[]):SeoEntry=>({
  title,description:`How Emissa structures ${problem} across supplier, product, material, evidence and approval records.`,h1:title,intro:`Product compliance becomes operational when ${problem} is connected to the exact supplier, component, material, product, requirement and evidence records behind the decision. Emissa provides that shared operating layer.`,keywords:[title.toLowerCase(),`${problem} software`,'product compliance software','supplier product compliance'],sections:[
    {title:'The product compliance data model',body:'A reliable system should not store declarations as isolated files. It should connect each source record to the product, component, supplier and requirement it supports.',bullets:fields},
    {title:'Evidence and scope',body:'Every declaration, certificate, test report or structured value should preserve supplier scope, product/component scope, issue date, review state, source file and the requirements that depend on it.'},
    {title:'Change impact',body:'Supplier, component, material or regulatory changes should make affected products visible so teams can review only the records that actually depend on the changed input.'},
    {title:'Connected workflows',body:'Product compliance evidence often supports more than one outcome. Emissa is designed to reuse approved records across buyer requests, due diligence, regulatory reporting, audits and product documentation.',bullets:related},
  ],faq:[['Is product compliance the same as supplier compliance?','They overlap. Product compliance depends on supplier and material evidence, while supplier compliance also includes due diligence, certificates, buyer requirements, risk and operational controls.'],['Can one declaration support multiple products?','Potentially, when its scope is correct and current. The system should preserve the relationship explicitly rather than relying on a copied file.'],['Does Emissa provide legal determinations?','No. Emissa manages the data, evidence and workflow around requirements defined by the customer and authoritative sources.']]});

export const productCompliancePages:Record<string,SeoEntry>={
  reach:pc('REACH Product Compliance Software','REACH supplier declarations and SVHC evidence',['Supplier and article/component','Candidate List/SVHC context','Declaration or substance evidence','Scope and effective date','Reviewer and status','Products affected'],['SCIP workflows','Buyer declarations','Supplier evidence requests','Product audit files']),
  rohs:pc('RoHS Product Compliance Software','RoHS supplier declarations and restricted-substance evidence',['Supplier and part/product','Declaration/test evidence','Restricted substance status','Exemption context where applicable','Review date','Products affected'],['Buyer evidence packages','Supplier certificate workflows','Product release reviews','Audit preparation']),
  pfas:pc('PFAS Product Compliance Software','PFAS supplier questionnaires, declarations and product evidence',['Supplier','Product/component','PFAS status or assertion','Substance/material context','Supporting evidence','Reviewer and exception state'],['TSCA/PFAS workflows','Buyer requests','Product risk review','Supplier remediation']),
  scip:pc('SCIP Product Compliance Data Management','SCIP article, component and SVHC evidence',['Article/component identifier','Supplier','SVHC/Candidate List information','Product hierarchy','Evidence source','Review status'],['REACH Article 33 communication','SCIP preparation','Product evidence packages','Supplier change review']),
  'conflict-minerals':pc('Conflict Minerals Product Compliance Software','3TG supplier declarations and due-diligence evidence',['Supplier','Product/component scope','CMRT or supporting declaration','Smelter/refiner context','Review date','Exception and follow-up'],['Supplier due diligence','Buyer questionnaires','Annual disclosure support','CAPA/remediation']),
  'material-declarations':pc('Material Declaration Management Software','supplier material declarations and composition evidence',['Supplier','Part/component','Material/substance declaration','Specification/version','Effective date','Approval status'],['REACH/RoHS/PFAS','Product footprints','DPP source data','Buyer requests']),
  'supplier-declarations':pc('Supplier Declaration Management Software','recurring supplier product-compliance declarations',['Supplier','Declaration type','Covered product/component','Issue/effective date','Source file','Reviewer and next review'],['Certificate management','Questionnaires','Product release','Customer evidence packages']),
  'digital-product-passports':pc('Digital Product Passport Data Management','supplier, material and product data that feed DPP workflows',['Product identifier/model','Economic operator','Supplier and material records','Required product attributes','Source evidence','Access/review state'],['DPP Registry preparation','Battery passport workflows','Product evidence','Supplier data reuse']),
  'battery-passports':pc('Battery Passport Data Management Software','battery model, supplier, composition, performance and lifecycle evidence',['Battery model/identifier','Economic operator','Supplier/material records','Performance and sustainability attributes','Evidence source','Review/version state'],['EU Battery Regulation workflows','DPP registration preparation','Supplier evidence','Product reporting']),
  'product-compliance-evidence':pc('Product Compliance Evidence Management','product evidence libraries tied to supplier and requirement scope',['Product/component','Supplier','Requirement','Evidence type','Version/effective date','Approval and expiration'],['Audit readiness','Buyer requests','Regulatory reviews','Change impact analysis']),
};
