import type { SeoEntry } from './seoExpansionContent';

export type Phase3Tool = {
  title:string; description:string; h1:string; intro:string; keywords:string[];
  questions:string[]; low:string; medium:string; high:string; cta:string;
};

const commercial=(name:string,problem:string,capabilities:string[]):SeoEntry=>({
  title:`${name} | Emissa`,
  description:`Enterprise ${name.toLowerCase()} for supplier evidence, requirements, ownership, approvals and audit-ready workflows.`,
  h1:name,
  intro:`Emissa turns ${problem} into a controlled supplier compliance workflow with reusable records, evidence, owners, deadlines and approval history.`,
  keywords:[name.toLowerCase(),`${name.toLowerCase()} software`,'supplier compliance software','supplier compliance platform'],
  sections:[
    {title:'The operating problem',body:`Teams often manage ${problem} across spreadsheets, email, shared drives and disconnected point tools. That makes status difficult to trust and forces the same supplier information to be collected repeatedly.`},
    {title:'What the system should control',body:'A production system should connect each requirement to the supplier, product or facility it affects, the evidence that supports it, the person responsible and the review decision.',bullets:capabilities},
    {title:'Why evidence reuse matters',body:'Validated supplier, facility, product and source records should be reusable across buyer requests, certificates, due diligence, product compliance, carbon, trade and packaging workflows.'},
    {title:'How Emissa fits',body:'Emissa is designed as a supplier compliance operating layer rather than a replacement for ERP, procurement, CRM or source regulatory systems. It links those records to compliance execution and proof.'},
  ],
  faq:[
    [`Who is ${name.toLowerCase()} for?`,'Manufacturers, exporters and enterprise suppliers that need repeatable supplier evidence, requirement and approval workflows.'],
    ['Can Emissa coexist with ERP and procurement systems?','Yes. The architecture is designed to consume relevant source-system data while preserving the original system of record.'],
    ['What should buyers test in a demo?','Use a real supplier record, assign a requirement, collect evidence, route an exception, approve the output and verify the audit trail.'],
  ],
});

export const commercialPages:Record<string,SeoEntry>={
  'supplier-compliance-software':commercial('Supplier Compliance Software','supplier requirements, evidence and approvals',['Supplier 360 records','Requirement assignment','Evidence collection and review','Expiration and deadline workflows','CAPA and remediation','Audit history']),
  'supplier-compliance-management-software':commercial('Supplier Compliance Management Software','cross-functional supplier compliance operations',['Executive readiness dashboards','Supplier-level status','Assigned obligations','Reusable evidence','Approval controls','Exception management']),
  'supplier-document-management-software':commercial('Supplier Document Management Software','supplier documents and supporting evidence',['Controlled evidence vault','Document ownership','Review and approval status','Expiration dates','Requirement relationships','Historical versions']),
  'supplier-certificate-management-software':commercial('Supplier Certificate Management Software','certificate collection, validation and expiration risk',['Certificate types and scopes','Issuer and effective dates','Expiration monitoring','Supplier reminders','Approval states','Requirements supported']),
  'supplier-due-diligence-software':commercial('Supplier Due Diligence Software','supplier due diligence and risk evidence',['Risk-based questionnaires','Evidence requests','Ownership and approvals','Finding management','Corrective actions','Decision history']),
  'supplier-risk-compliance-software':commercial('Supplier Risk Compliance Software','supplier risk findings that must become accountable compliance work',['Risk scoring context','Requirement gaps','Evidence status','Open findings','CAPA','Leadership rollups']),
  'supplier-questionnaire-software':commercial('Supplier Questionnaire Software','recurring supplier questionnaires and evidence requests',['Conditional requirements','Reusable responses','Evidence attachments','Reviewer workflows','Reminders','Approval history']),
  'supplier-audit-management-software':commercial('Supplier Audit Management Software','supplier audit preparation, findings and evidence',['Audit scope','Evidence package','Findings','Owners','Corrective action','Closure verification']),
  'supplier-capa-software':commercial('Supplier CAPA Software','supplier corrective and preventive action workflows',['Finding intake','Root cause','Containment','Corrective action','Preventive action','Verification and closure']),
  'supplier-onboarding-software':commercial('Supplier Compliance Onboarding Software','compliance onboarding before suppliers enter production workflows',['Profile collection','Requirement assignment','Questionnaires','Certificates','Approval gates','ERP/procurement handoff']),
};

const platform=(name:string,job:string,features:string[]):SeoEntry=>({
  title:`${name} | Emissa Platform`,
  description:`Explore ${name}, Emissa's ${job} capability for enterprise supplier compliance teams.`,
  h1:name,
  intro:`${name} is the ${job} layer inside Emissa Supplier Compliance Infrastructure. It connects operational status to the source records and evidence behind every decision.`,
  keywords:[`${name.toLowerCase()} supplier compliance`,`${name.toLowerCase()} software`,'supplier compliance platform'],
  sections:[
    {title:'What this module controls',body:`${name} is designed to make ${job} visible, accountable and auditable without forcing teams to rebuild source data in a separate point solution.`,bullets:features},
    {title:'Shared supplier compliance graph',body:'Every module works against the same supplier, facility, product, requirement, evidence, owner and approval relationships so teams can reuse validated information instead of duplicating it.'},
    {title:'Enterprise controls',body:'Production workflows should preserve permissions, source-system lineage, timestamps, review status and historical change so leadership metrics remain traceable to operating records.'},
    {title:'Implementation',body:'Emissa implementations map source systems, supplier populations, requirement libraries, evidence types, ownership and approval logic into one operating model.'},
  ],
  faq:[['Is this a separate product?','No. It is a module within the broader Emissa supplier compliance operating layer.'],['Can it use data from other systems?','Yes. Relevant ERP, procurement, accounting, CRM and structured file/API data can be mapped into Emissa when the connector and customer permissions are configured.'],['Can access be role-based?','The product architecture is designed for tenant-aware permissions and workflow ownership.']],
});

export const platformPages:Record<string,SeoEntry>={
  'supplier-360':platform('Supplier 360','supplier system-of-record',['Supplier profile','Facilities and products','Requirements','Evidence status','Risk and findings','Activity history']),
  'evidence-vault':platform('Evidence Vault','controlled supplier evidence management',['Source files and metadata','Evidence-to-requirement mapping','Approval state','Expiration dates','Owner','Audit history']),
  'workflow-studio':platform('Workflow Studio','requirement and obligation orchestration',['Assigned work','Due dates','Requirement type','Evidence dependencies','Review stages','Escalation']),
  'regulatory-intelligence':platform('Regulatory Intelligence','regulatory requirement and change context',['Requirement library','Official sources','Applicability context','Effective dates','Affected workflows','Review ownership']),
  'network-risk':platform('Network Risk','supplier network risk visibility',['Supplier risk rollups','Evidence gaps','Overdue obligations','Concentration signals','Open CAPA','Executive prioritization']),
  capa:platform('Corrective Action Management','supplier CAPA and remediation',['Finding','Root cause','Containment','Corrective action','Preventive action','Verification and closure']),
  'supplier-communications':platform('Supplier Communications','outbound supplier request and reminder workflow',['Evidence request emails','Reminder cadence','Owner context','Supplier response links','Escalation','Audit events']),
  'ai-compliance-copilot':platform('AI Compliance Copilot','compliance intelligence and operator assistance',['Supplier status summaries','Evidence-gap context','Requirement prioritization','Workflow navigation','Data-grounded recommendations','Human review']),
  'buyer-requests':platform('Buyer Compliance Requests','customer evidence-response operations',['Buyer requirement intake','Evidence reuse','Account-specific packages','Approval workflow','Response status','Delivery history']),
  reporting:platform('Compliance Reporting','executive and operational readiness reporting',['Compliance score','Open obligations','Expiring evidence','Supplier risk','Workflow throughput','Audit-ready exports']),
};

const reg=(title:string,description:string,intro:string,keywords:string[],sections:SeoEntry['sections'],sources:{label:string;url:string}[],faq:[string,string][],note?:string):SeoEntry=>({title,description,h1:title.replace(' Guide',''),intro,keywords,sections,sources,faq,note});

export const phase3Regulations:Record<string,SeoEntry>={
  'epr-california':reg('California SB 54 Packaging EPR Guide','Supplier and packaging data workflow guidance for California SB 54 packaging producer responsibility.','California SB 54 creates a statewide producer-responsibility system for single-use packaging and plastic food service ware. Emissa can organize producer, product, packaging, supplier and source-evidence records around the obligations defined by CalRecycle.',['California SB 54 software','California packaging EPR','SB 54 producer data'],[
    {title:'Current program status',body:'CalRecycle states that permanent SB 54 regulations were approved and became effective on May 1, 2026. Circular Action Alliance is the first approved Producer Responsibility Organization.'},
    {title:'Covered material data',body:'CalRecycle maintains covered material categories that combine material type and form. A scalable internal model should map packaging components and products to those categories with source evidence.'},
    {title:'Producer workflow',body:'Companies need a controlled way to determine producer identity, map products and packaging, preserve exemptions or exclusions where applicable, support PRO reporting and retain the evidence behind submitted values.'},
    {title:'Emissa operating layer',body:'Emissa can maintain packaging masters, supplier specifications, ownership, review status and reporting-period evidence so the same approved data can support EPR, buyer and product workflows.'},
  ],[{label:'CalRecycle — SB 54 Packaging EPR',url:'https://calrecycle.ca.gov/packaging/packaging-epr/'},{label:'CalRecycle — Covered Material Categories',url:'https://calrecycle.ca.gov/packaging/packaging-epr/cmclist/'}],[['When did permanent SB 54 regulations take effect?','CalRecycle states May 1, 2026.'],['What materials are covered?','The law covers single-use packaging and single-use plastic food service ware subject to statutory definitions, exclusions and exemptions.'],['Does Emissa determine legal producer status?','No. Emissa organizes customer-defined requirements and evidence; legal applicability should be confirmed against current CalRecycle guidance.']]),
  'epr-oregon':reg('Oregon Recycling Modernization Act EPR Guide','Operational data guidance for Oregon packaging, paper and food-serviceware producer responsibilities.','Oregon’s Recycling Modernization Act shifted key recycling-system costs and reporting responsibilities toward producers of covered products. Emissa can structure the supplier, product, packaging and evidence layer around those workflows.',['Oregon EPR software','Oregon Recycling Modernization Act producer','Oregon packaging compliance'],[
    {title:'Program is operating',body:'Oregon DEQ states that recycling-program changes started in July 2025. From 2025 onward, covered producers generally must register with an approved PRO, report supply data and pay fees unless an exemption applies.'},
    {title:'Covered-product master',body:'Internal systems should map packaging, paper and food-serviceware records to products, suppliers and source evidence before values are aggregated for PRO reporting.'},
    {title:'Exemptions and change',body:'Oregon maintains small-producer and covered-product exemption pathways. Teams should preserve the basis and evidence for any exemption determination and monitor rule updates.'},
    {title:'Emissa workflow',body:'Emissa can connect material and product data to evidence, reporting periods, ownership and review history while preserving the source system that owns purchasing or product master data.'},
  ],[{label:'Oregon DEQ — Recycling Modernization Act',url:'https://www.oregon.gov/deq/recycling/pages/modernizing-oregons-recycling-system.aspx'},{label:'Oregon DEQ — Producers of Covered Products',url:'https://www.oregon.gov/deq/recycling/Pages/Producers-of-Covered-Products.aspx'}],[['When did Oregon program changes begin?','Oregon DEQ states that program changes began in July 2025.'],['Do all producers have the same obligations?','No. Producer definitions, small-producer thresholds and product exemptions can change the applicable obligations.'],['Can Emissa replace the PRO?','No. Emissa manages enterprise data and workflow around external reporting and producer-responsibility processes.']]),
  'epr-maine':reg('Maine Packaging Stewardship EPR Guide','Current producer data and evidence guidance for Maine’s Stewardship Program for Packaging.','Maine’s packaging stewardship program is moving through implementation. Emissa can prepare producer, product, packaging and supplier data so teams are ready for registration, reporting and invoicing workflows as official mechanisms come online.',['Maine packaging EPR','Maine stewardship packaging producer','Maine EPR software'],[
    {title:'Current implementation stage',body:'Maine DEP states that the program is currently at the step of contracting with a Stewardship Organization. On August 20, 2026 DEP reported that no proposals were submitted by the prior RFP deadline and a revised implementation schedule will follow selection of the organization.'},
    {title:'Producer registration and reporting',body:'DEP states that producers will register after the Stewardship Organization makes a registration mechanism available. Annual reporting is expected to use defined packaging material types.'},
    {title:'Prepare data now',body:'A producer should maintain packaging material types, quantities, product relationships, supplier evidence and the methodology used to estimate Maine-relevant amounts rather than waiting for a reporting portal.'},
    {title:'Emissa workflow',body:'Emissa can preserve packaging masters, supplier source files, ownership and review status while keeping reporting-period values traceable.'},
  ],[{label:'Maine DEP — Stewardship Program for Packaging',url:'https://www.maine.gov/dep/waste/recycle/epr.html'}],[['Is Maine producer registration open?','DEP indicates registration will follow availability of the Stewardship Organization registration mechanism; check the current DEP implementation page.'],['What should producers maintain internally?','Packaging material type, quantities, product relationships, producer status, source evidence and reporting-period records.'],['Does Emissa submit directly to Maine DEP?','This page describes the internal compliance data layer; any production submission integration would need to match the final official process.']], 'Maine implementation dates are evolving. Verify the current DEP schedule before relying on a deadline.'),
  'epr-minnesota':reg('Minnesota Packaging EPR Guide','Producer-responsibility data and supplier evidence guidance for Minnesota’s Packaging Waste and Cost Reduction Act.','Minnesota is building its statewide packaging EPR program through the Packaging Waste and Cost Reduction Act. Emissa can structure the product, packaging, supplier and evidence records needed as stewardship planning and rulemaking progress.',['Minnesota packaging EPR','PWCRA software','Minnesota producer responsibility'],[
    {title:'Program architecture',body:'MPCA states that producers of packaging, food packaging and paper products are required to join a producer responsibility organization and help fund end-of-life management of covered materials.'},
    {title:'Implementation timeline',body:'MPCA describes 2025–2026 as foundation-building, 2027–2028 as structural development, and 2029–2032 as stewardship-plan implementation and performance tracking.'},
    {title:'Data readiness',body:'Producer teams should establish reusable packaging, product, market and supplier records before reporting obligations mature so stewardship-plan requests do not become spreadsheet reconstruction projects.'},
    {title:'Emissa workflow',body:'Emissa can link packaging attributes and evidence to suppliers, products, owners and reporting periods while keeping external PRO relationships separate.'},
  ],[{label:'Minnesota PCA — Extended producer responsibility for packaging',url:'https://www.pca.state.mn.us/air-water-land-climate/extended-producer-responsibility-for-packaging'},{label:'Minnesota PCA — PWCRA rulemaking',url:'https://www.pca.state.mn.us/get-engaged/packaging-waste-and-cost-reduction-act'}],[['Has Minnesota selected an initial PRO?','MPCA confirmed Circular Action Alliance as Minnesota’s initial packaging PRO.'],['When does the system fully mature?','MPCA’s public timeline phases implementation through 2032.'],['Does every product use the same data?','No. Covered-material definitions, exemptions and future program rules determine applicability.']]),
  'epr-maryland':reg('Maryland Packaging and Paper Products EPR Guide','Supplier, producer and covered-material data guidance for Maryland packaging producer responsibility.','Maryland’s Packaging and Paper Products – Producer Responsibility Plans Act now has implementing regulations. Emissa can structure producer, material, supplier and evidence records around registration, reporting and plan workflows.',['Maryland packaging EPR','Maryland producer responsibility software','COMAR packaging producer responsibility'],[
    {title:'Current status',body:'Maryland MDE states that the Packaging and Paper Products – Producer Responsibility Plans Act was signed in 2025 and implementing regulations became effective May 25, 2026.'},
    {title:'Producer and covered-material records',body:'The regulations address producer definitions, covered materials, exclusions, registration, reporting and recordkeeping. Internal systems should preserve how each product and packaging stream was classified.'},
    {title:'PRO relationship',body:'MDE identifies Circular Action Alliance as the approved Producer Responsibility Organization for the program. Enterprise records should retain the values and evidence supplied externally.'},
    {title:'Emissa workflow',body:'Emissa can connect producer and brand context to products, packaging data, suppliers, reporting periods, evidence and approvals.'},
  ],[{label:'Maryland MDE — Producer Responsibility',url:'https://mde.maryland.gov/programs/land/WasteManagement/Pages/ProducerResponsibility.aspx'},{label:'Maryland MDE — Adopted Land Regulations',url:'https://mde.maryland.gov/PROGRAMS/REGULATIONS/LAND/Pages/Adopted.aspx'}],[['When did Maryland implementing regulations become effective?','MDE lists May 25, 2026.'],['Is there an approved PRO?','MDE identifies Circular Action Alliance as the approved PRO for packaging and paper products.'],['What should internal records preserve?','Producer and brand identity, product and covered-material classification, source evidence, reporting values, review status and history.']]),
  'epr-colorado':reg('Colorado Producer Responsibility Packaging EPR Guide','Operational packaging data guidance for Colorado’s statewide producer responsibility program.','Colorado’s Producer Responsibility Program for Statewide Recycling requires companies that sell covered packaging, paper products and food-service ware to help fund the statewide recycling system. Emissa can prepare the underlying supplier and product data.',['Colorado packaging EPR','Colorado producer responsibility software','HB 22-1355 compliance'],[
    {title:'Program foundation',body:'Colorado CDPHE states that HB 22-1355 established a producer responsibility program for companies selling products in packaging, paper products and food service ware.'},
    {title:'Internal data model',body:'Teams should map covered material, product, producer and market records to source evidence so reported quantities remain reproducible.'},
    {title:'Design and fee context',body:'Producer responsibility programs can use material and design characteristics to influence fees and system outcomes. A clean packaging master helps teams evaluate those effects consistently.'},
    {title:'Emissa workflow',body:'Emissa can connect packaging attributes and supplier source files to product, owner, review and external reporting workflows.'},
  ],[{label:'Colorado CDPHE — Recycling and Producer Responsibility',url:'https://cdphe.colorado.gov/hm/recycling'}],[['What law created Colorado’s statewide program?','CDPHE identifies House Bill 22-1355.'],['Which broad material categories are involved?','CDPHE describes packaging, paper products and food service ware within the program.'],['Does Emissa calculate official fees?','Not by default. Emissa organizes the underlying data and workflow; official fee calculations depend on current program and PRO rules.']]),
  'epr-uk':reg('UK Extended Producer Responsibility for Packaging Guide','Data, registration and evidence workflow guidance for UK packaging EPR.','UK packaging EPR requires obligated organizations to register and report packaging information under the current producer-responsibility framework. Emissa can structure product, packaging, organization and evidence records before submission.',['UK EPR packaging software','UK packaging EPR reporting','PackUK producer data'],[
    {title:'Current guidance',body:'GOV.UK maintains live guidance for determining obligations, registering and creating registration files. Guidance was updated in August 2026 for the current registration process.'},
    {title:'Organization and brand data',body:'Registration workflows can require organization, brand, partner and compliance-scheme information. Internal records should retain the exact source and effective period for each value.'},
    {title:'Packaging data layer',body:'A scalable model connects packaging components and weights to products, markets and reporting periods rather than rebuilding aggregate files from scratch each cycle.'},
    {title:'Emissa workflow',body:'Emissa can maintain packaging masters, supplier evidence, ownership and review status, then produce controlled datasets for the required external process.'},
  ],[{label:'GOV.UK — Check if you must comply with EPR for packaging',url:'https://www.gov.uk/guidance/check-if-you-must-comply-with-epr-for-packaging--2'},{label:'GOV.UK — Create your registration file',url:'https://www.gov.uk/guidance/register-for-epr-for-packaging-create-your-registration-file'}],[['Where should UK obligations be checked?','Use current GOV.UK EPR for packaging guidance and the applicable regulator or compliance scheme.'],['Can registration requirements change?','Yes. Guidance and technical interpretations are updated, so teams should maintain a reviewed requirement record.'],['What does Emissa add?','A reusable internal product, packaging, supplier and evidence layer around the external registration and reporting process.']]),
  'cbam-steel':reg('CBAM Steel Supplier Data Guide','Embedded-emissions evidence workflow guidance for iron and steel products potentially covered by EU CBAM.','Steel CBAM workflows require product classification, production-installation data, embedded-emissions inputs and evidence that can be reused across importer requests. Emissa can structure those relationships.',['CBAM steel software','steel embedded emissions supplier data','CBAM iron steel compliance'],[
    {title:'Product and CN context',body:'Start with the product and customs classification that determines whether a good is within the applicable CBAM scope.'},
    {title:'Installation evidence',body:'Link production installation, reporting period, production quantity, methodology and source activity data to the product records that depend on them.'},
    {title:'Reusable importer response',body:'Approved installation and emissions records should be reusable across shipments and importer requests without losing version history.'},
    {title:'Emissa workflow',body:'Emissa can connect products, facilities, emissions records, evidence, owners and approvals in one CBAM-ready operating model.'},
  ],[{label:'European Commission — CBAM definitive regime',url:'https://taxation-customs.ec.europa.eu/carbon-border-adjustment-mechanism/cbam-definitive-regime_en'}],[['Is all steel automatically covered?','No. Scope depends on the applicable CN codes and current CBAM rules.'],['Should suppliers keep installation-level evidence?','A defensible workflow should preserve the installation and methodology information supporting communicated embedded-emissions values.'],['Does Emissa determine customs classification?','No. Classification and applicability should be confirmed by qualified teams using current official guidance.']]),
  'cbam-aluminium':reg('CBAM Aluminium Supplier Data Guide','Supplier, installation and embedded-emissions evidence guidance for aluminium CBAM workflows.','Aluminium suppliers responding to CBAM requests need repeatable product, installation, emissions and source-evidence records. Emissa can preserve that operating model across customers and reporting periods.',['CBAM aluminium software','aluminum CBAM supplier data','embedded emissions aluminium'],[
    {title:'Classify before calculating',body:'Identify the product and applicable CN code before building the emissions workflow.'},
    {title:'Installation-level source data',body:'Preserve production volumes, direct and applicable indirect emissions inputs, methodology, source records and review status.'},
    {title:'Version control',body:'When methodology or source values change, prior importer responses should remain traceable to the version actually released.'},
    {title:'Emissa workflow',body:'Emissa can connect installation data and evidence to products, customers, shipments, owners and approved response packages.'},
  ],[{label:'European Commission — CBAM definitive regime',url:'https://taxation-customs.ec.europa.eu/carbon-border-adjustment-mechanism/cbam-definitive-regime_en'}],[['Are all aluminium products covered?','No. Current CN-code scope determines applicability.'],['Why preserve versions?','The value communicated to an importer should remain traceable to the source data and methodology used at that time.'],['Can the same installation data support multiple importers?','Yes, when the scope and reporting period are appropriate and the data has been reviewed for the intended use.']]),
  'eudr-coffee':reg('EUDR Coffee Supplier Traceability Guide','Supplier, plot, commodity and due-diligence evidence guidance for coffee supply chains under EUDR.','Coffee EUDR readiness depends on traceable supplier, production-origin and due-diligence records. Emissa can link those records to evidence and review workflows before external statements are submitted.',['EUDR coffee software','coffee deforestation due diligence','coffee supplier traceability EUDR'],[
    {title:'Supplier and origin graph',body:'Connect supplier and intermediary records to production-origin information and the specific commodity or product records they support.'},
    {title:'Evidence quality',body:'Separate verified location and due-diligence evidence from supplier assertions, missing records and unresolved exceptions.'},
    {title:'Risk and remediation',body:'Potential gaps should become assigned work with owners, deadlines and closure evidence rather than remaining as notes in a spreadsheet.'},
    {title:'Emissa workflow',body:'Emissa can preserve origin evidence, review status, risk findings, approvals and external statement identifiers against reusable supplier records.'},
  ],[{label:'European Commission — EUDR',url:'https://environment.ec.europa.eu/topics/forests/deforestation/regulation-deforestation-free-products_en'}],[['Is coffee within EUDR commodity scope?','Coffee is one of the commodities identified in the Regulation; exact product scope depends on the relevant commodity and product provisions.'],['What is the internal system’s job?','Maintain traceable supplier, origin, evidence, review and due-diligence records before information reaches the official external process.'],['Does Emissa replace the EU Information System?','No. It manages enterprise source data and workflow around required submissions.']]),
  'eudr-cocoa':reg('EUDR Cocoa Supplier Traceability Guide','Supplier, origin and due-diligence evidence guidance for cocoa supply chains under EUDR.','Cocoa supply chains can involve multiple intermediaries and origin records. Emissa can connect supplier, production-origin, product and review evidence into one due-diligence operating layer.',['EUDR cocoa software','cocoa deforestation due diligence','cocoa supplier traceability'],[
    {title:'Trace origin relationships',body:'Map supplier and intermediary relationships to production-origin evidence and the product or lot records that depend on them.'},
    {title:'Do not flatten uncertainty',body:'Keep verified evidence, supplier assertions, missing data and unresolved risk findings as distinct states.'},
    {title:'Evidence reuse',body:'Approved supplier and origin records can support recurring customer requests and due-diligence workflows when their scope remains valid.'},
    {title:'Emissa workflow',body:'Emissa can connect origin evidence, risk review, owner actions, approvals and external statement identifiers to the supplier compliance record.'},
  ],[{label:'European Commission — EUDR',url:'https://environment.ec.europa.eu/topics/forests/deforestation/regulation-deforestation-free-products_en'}],[['Is cocoa in EUDR scope?','Cocoa is one of the commodities identified in the Regulation; confirm exact product applicability against current official rules.'],['Why track intermediaries?','Traceability and due diligence can depend on understanding the chain between the economic operator and production origin.'],['Can Emissa prove legal compliance by itself?','No. It supports the data, evidence and workflow used by the customer’s due-diligence process.']]),
};

const tpl=(name:string,fields:string[]):SeoEntry=>({
  title:`${name} Template`,description:`Download and operationalize a ${name.toLowerCase()} structure for supplier compliance teams.`,h1:`${name} Template`,intro:'Use a structured template to define the fields, evidence, ownership and review states before the workflow is automated in Emissa.',keywords:[`${name.toLowerCase()} template`,'supplier compliance template'],sections:[{title:'Recommended fields',body:'Use these fields as a starting point and tailor them to supplier type, product, geography, risk and business relationship.',bullets:fields},{title:'Evidence and ownership',body:'Every material assertion should have a source record, responsible owner and review state. Expiring evidence should also carry an effective or expiration date.'},{title:'Approval logic',body:'Separate submission from approval. Exceptions should create assigned remediation instead of disappearing into comments or email.'},{title:'From CSV to workflow',body:'Once the structure is validated, configure the same fields and requirements in Emissa so reminders, reviews and audit history are controlled.'}],faq:[['Can I start in a spreadsheet?','Yes. The downloadable template is designed to help establish a clean data model before automation.'],['Should every supplier receive every requirement?','No. Requirements should be assigned based on applicability, product, geography, risk and relationship.'],['Can this become an Emissa workflow?','Yes. The same fields can be mapped into controlled supplier requirements, evidence requests and review steps.']]});

export const phase3Templates:Record<string,SeoEntry>={
  'supplier-onboarding-checklist':tpl('Supplier Onboarding Checklist',['Supplier legal identity','Facilities and ownership','Products/services supplied','Applicable compliance requirements','Required certificates','Risk tier','Approvers','Go-live decision']),
  'supplier-audit-checklist':tpl('Supplier Audit Checklist',['Audit scope','Requirement','Evidence requested','Evidence received','Finding','Severity','Owner','CAPA required','Closure status']),
  'supplier-risk-questionnaire':tpl('Supplier Risk Questionnaire',['Business continuity','Regulatory exposure','Product/material risk','Geographic risk','Labor and due diligence controls','Certificates','Evidence links','Attestation']),
  'reach-declaration-tracker':tpl('REACH Declaration Tracker',['Supplier','Article/component','Declaration date','SVHC/Candidate List status','Evidence file','Scope','Reviewer','Next review date']),
  'rohs-declaration-tracker':tpl('RoHS Declaration Tracker',['Supplier','Part/product','Declaration date','Restricted substance status','Exemption reference if applicable','Evidence file','Reviewer','Next review date']),
  'pfas-supplier-questionnaire':tpl('PFAS Supplier Questionnaire',['Supplier and product scope','PFAS intentionally added status','Substance or material information','Manufacturing context','Supporting declaration','Reviewer','Exception','Next action']),
  'eudr-supplier-questionnaire':tpl('EUDR Supplier Questionnaire',['Supplier','Commodity/product','Country/region of production','Production-origin evidence','Traceability identifiers','Risk review','Supporting evidence','Approval status']),
  'digital-product-passport-checklist':tpl('Digital Product Passport Data Checklist',['Product identifier','Model/version','Economic operator','Supplier and material records','Required sustainability fields','Evidence source','Access class','Review/registration status']),
};

export const phase3Tools:Record<string,Phase3Tool>={
  'supplier-compliance-maturity-assessment':{title:'Supplier Compliance Maturity Assessment',description:'Score your supplier compliance operating model across evidence, workflows, ownership, integrations and audit readiness.',h1:'Supplier Compliance Maturity Assessment',intro:'Measure whether your current operating model is reactive, structured, controlled or infrastructure-ready.',keywords:['supplier compliance maturity assessment','supplier compliance score'],questions:['Do you have one supplier compliance system of record?','Are requirements assigned by supplier, product, geography or risk?','Is evidence linked directly to the requirements it supports?','Are expiration dates and deadlines automated?','Are supplier responses reviewed separately from supplier submission?','Do exceptions create assigned corrective actions?','Can approved evidence be reused across buyer and regulatory workflows?','Can leadership trace dashboard status back to source evidence?','Are ERP/procurement source records connected rather than re-keyed?','Can you reconstruct who approved a compliance decision and when?'],low:'Reactive: compliance depends heavily on manual reconstruction. Prioritize one supplier/evidence model, ownership and deadline controls.',medium:'Structured: core controls exist, but evidence reuse, integration or cross-workflow governance can still be strengthened.',high:'Controlled/Infrastructure-ready: the operating model has strong evidence, ownership and audit controls. Focus on scale, automation and data reuse.',cta:'Map the gaps into Emissa workflows.'},
  'supplier-certificate-risk-calculator':{title:'Supplier Certificate Risk Assessment',description:'Estimate certificate-management risk based on ownership, expiration monitoring, review controls and supplier scale.',h1:'Supplier Certificate Risk Assessment',intro:'Test whether your certificate process can reliably prevent expired or unreviewed evidence from supporting compliance decisions.',keywords:['supplier certificate risk calculator','certificate expiration risk'],questions:['Is every certificate tied to a specific supplier and scope?','Do you capture issuer, effective date and expiration date?','Are reminders automated before expiration?','Is renewal ownership assigned?','Is certificate validity reviewed before approval?','Can you see every requirement a certificate supports?','Do expired documents automatically become unusable or flagged?','Can leadership see upcoming certificate exposure?'],low:'High exposure: certificate risk is largely manual or invisible. Centralize scope, expiration, ownership and review status first.',medium:'Moderate exposure: basic tracking exists, but automation or evidence-to-requirement relationships are incomplete.',high:'Lower exposure: certificate ownership, timing and approval controls are structured. Continue monitoring exceptions and scale.',cta:'Centralize certificates in Evidence Vault.'},
  'supplier-evidence-coverage':{title:'Supplier Evidence Coverage Assessment',description:'Assess whether supplier evidence coverage is complete, verified, current and reusable.',h1:'Supplier Evidence Coverage Assessment',intro:'A high document count is not the same as high evidence coverage. Score whether requirements are actually supported by current approved proof.',keywords:['supplier evidence coverage','supplier evidence calculator'],questions:['Can you list every applicable requirement for a supplier?','Does every requirement show whether evidence is missing, submitted or approved?','Can evidence support more than one requirement where appropriate?','Do you distinguish supplier assertion from internally approved evidence?','Are evidence scopes tied to the correct supplier/product/facility?','Are expirations and review dates tracked?','Can missing evidence create assigned work?','Can you export an audit-ready evidence matrix?'],low:'Low coverage control: the organization may have documents but cannot reliably prove requirement-level coverage.',medium:'Partial coverage control: the main structure exists, but review, scope or reuse gaps remain.',high:'Strong coverage control: requirement-level evidence status is visible and traceable. Focus on automation and exception handling.',cta:'Build an evidence matrix in Emissa.'},
  'buyer-compliance-readiness':{title:'Buyer Compliance Request Readiness Assessment',description:'Score how quickly your team can answer customer compliance requests with approved reusable evidence.',h1:'Buyer Compliance Request Readiness Assessment',intro:'Test whether customer questionnaires and evidence requests can be answered from approved source records instead of reconstructed manually.',keywords:['buyer compliance request readiness','supplier questionnaire readiness'],questions:['Do you track buyer-specific requirements separately from internal requirements?','Can approved evidence be reused across customers?','Can you see who owns each unanswered request?','Are response deadlines tracked?','Can sensitive evidence be reviewed before release?','Can you identify which supplier/product records support a buyer answer?','Can the final delivered package be reconstructed later?','Can repeated questionnaire fields reuse prior approved responses?'],low:'Reactive buyer response: repeated requests are likely being rebuilt manually and may create inconsistent answers.',medium:'Structured buyer response: reusable information exists, but ownership, approval or delivery history needs work.',high:'High readiness: buyer requests are connected to reusable evidence, owners and approvals. Focus on scale and automation.',cta:'Run buyer requests through Emissa.'},
  'cbam-readiness':{title:'CBAM Supplier Data Readiness Assessment',description:'Assess product, installation, embedded-emissions and evidence readiness for recurring CBAM data requests.',h1:'CBAM Supplier Data Readiness Assessment',intro:'Score whether your organization can produce repeatable, traceable CBAM supplier information for covered goods and importer requests.',keywords:['CBAM readiness calculator','CBAM supplier data assessment'],questions:['Are potentially covered products mapped to current customs/CN context?','Are production installations linked to the products they produce?','Are reporting periods and production quantities controlled?','Are emissions inputs traceable to source evidence?','Is methodology/version history preserved?','Are responsible reviewers assigned?','Can approved installation data be reused across importer requests?','Can you reconstruct the exact data package released for a prior request?'],low:'Low CBAM data readiness: product, installation or source-evidence relationships are incomplete.',medium:'Partial readiness: key data exists, but repeatability, version control or approval workflow needs strengthening.',high:'Strong operational readiness: product, installation, evidence and approval relationships are controlled. Continue validating legal scope and methodology.',cta:'Structure CBAM data in Emissa.'},
  'eudr-readiness':{title:'EUDR Supplier Due Diligence Readiness Assessment',description:'Assess supplier, commodity, origin, traceability and due-diligence evidence readiness for EUDR workflows.',h1:'EUDR Supplier Due Diligence Readiness Assessment',intro:'Score whether supplier and origin information can support a repeatable due-diligence process before external statements are submitted.',keywords:['EUDR readiness assessment','EUDR due diligence tool'],questions:['Are relevant commodities/products mapped to current EUDR scope?','Can suppliers and intermediaries be linked to production-origin records?','Is origin/geolocation evidence preserved with source metadata?','Can missing or conflicting evidence be distinguished from verified data?','Are risk assessments tied to the evidence reviewed?','Do risk findings create assigned mitigation work?','Can approval decisions be reconstructed?','Can internal records be reconciled to external due-diligence statement identifiers?'],low:'Low EUDR readiness: traceability, evidence or due-diligence controls are too fragmented for repeatable execution.',medium:'Partial readiness: core supplier/origin records exist, but risk, evidence quality or auditability needs improvement.',high:'Strong operational readiness: supplier, origin, evidence and decision records are controlled. Continue verifying scope and current regulatory requirements.',cta:'Build EUDR due diligence workflows in Emissa.'},
};

export const regulatoryCalendar=[
  {date:'2026-01-01',title:'EU CBAM definitive regime',status:'Active',href:'/regulations/cbam',source:'https://taxation-customs.ec.europa.eu/carbon-border-adjustment-mechanism/cbam-definitive-regime_en'},
  {date:'2026-05-01',title:'California SB 54 permanent regulations effective',status:'Active',href:'/regulations/epr-california',source:'https://calrecycle.ca.gov/packaging/packaging-epr/'},
  {date:'2026-05-25',title:'Maryland packaging producer-responsibility regulations effective',status:'Active',href:'/regulations/epr-maryland',source:'https://mde.maryland.gov/PROGRAMS/REGULATIONS/LAND/Pages/Adopted.aspx'},
  {date:'2026-07-20',title:'EU Digital Product Passport Registry operational',status:'Active',href:'/regulations/espr-digital-product-passport',source:'https://single-market-economy.ec.europa.eu/single-market/digital-product-passport/dpp-registry_en'},
  {date:'2026-12-30',title:'EUDR application date for large and medium operators',status:'Upcoming',href:'/regulations/eudr',source:'https://environment.ec.europa.eu/topics/forests/deforestation/regulation-deforestation-free-products_en'},
  {date:'2027-02-18',title:'EU battery passport requirement for specified battery categories',status:'Upcoming',href:'/regulations/eu-battery-passport',source:'https://eur-lex.europa.eu/eli/reg/2023/1542/2023-07-28'},
  {date:'2027-06-30',title:'EUDR application date for micro and small operators',status:'Upcoming',href:'/regulations/eudr',source:'https://environment.ec.europa.eu/topics/forests/deforestation/regulation-deforestation-free-products_en'},
];
