import type { SeoEntry } from './seoExpansionContent';

const integration = (name:string, system:string, data:string[], outcomes:string[]):SeoEntry => ({
  title:`${name} Supplier Compliance Integration`,
  description:`See how ${name} data can feed supplier compliance, evidence, due diligence and regulatory workflows in Emissa.`,
  h1:`${name} + Emissa Supplier Compliance Integration`,
  intro:`Connect ${system} records to the supplier compliance operating layer without changing which source system owns the underlying business data.`,
  keywords:[`${name} supplier compliance integration`,`${name} compliance integration`,`${name} supplier data`,`supplier compliance integrations`],
  sections:[
    {title:'Source data to preserve',body:`A production ${name} integration should preserve record identifiers, timestamps, ownership and source-system lineage so compliance teams can prove where imported data originated.`,bullets:data},
    {title:'Compliance workflows the data can support',body:'The highest-value integrations connect source data directly to requirements, evidence requests, approvals and reusable supplier records.',bullets:outcomes},
    {title:'Implementation controls',body:'Authentication, field mapping, sync frequency, error handling and write-back behavior should be documented during implementation. Imported data should remain distinguishable from reviewed or approved compliance outputs.'},
    {title:'Availability',body:`Connector scope depends on the APIs, permissions and deployment configuration enabled for ${name}. Emissa confirms exact objects and supported flows during implementation.`},
  ],
  faq:[
    [`Does Emissa replace ${name}?`,`No. ${name} remains the source system for the records it owns while Emissa uses relevant data in supplier compliance workflows.`],
    ['Can the same imported data support more than one requirement?','Yes. Reuse is a core design goal: one validated supplier, product, facility or transaction record can support multiple compliance workflows.'],
    ['Is every object available automatically?','No. Available objects depend on source-system APIs, customer permissions and implementation configuration.'],
  ],
  note:'Integration availability and supported objects vary by customer environment and API permissions.',
});

export const phase2Integrations:Record<string,SeoEntry> = {
  'sap-s4hana': integration('SAP S/4HANA','enterprise resource planning',['Business partner and supplier master data','Purchase orders and purchasing history','Material and product masters','Plants, company codes and locations'],['Supplier master enrichment','Product and material compliance','CBAM and product evidence mapping','Multi-entity supplier reporting']),
  'oracle-erp': integration('Oracle Fusion Cloud ERP','enterprise resource planning',['Supplier master records','Purchase orders and invoices','Items and categories','Business units and locations'],['Supplier due diligence context','Spend and supplier prioritization','Product compliance evidence','Cross-entity compliance reporting']),
  'dynamics-365': integration('Microsoft Dynamics 365','ERP and business operations',['Vendors and accounts','Purchase orders and invoices','Products and inventory records','Sites and legal entities'],['Supplier onboarding','Evidence requests','Buyer requirement response','Product and facility compliance']),
  workday: integration('Workday','enterprise and workforce operations',['Organization structures','Supplier or business-partner context where configured','Ownership and responsibility data','Business process references'],['Workflow ownership','Entity mapping','Escalation routing','Due-diligence accountability']),
  snowflake: integration('Snowflake','cloud data platform',['Curated supplier datasets','Purchasing and spend tables','Product and facility datasets','Historical compliance source data'],['Large-scale supplier ingestion','Analytics-ready compliance data','Cross-system evidence joins','Enterprise reporting']),
  'microsoft-teams': integration('Microsoft Teams','collaboration and communication',['Workflow notifications','Owner reminders','Approval prompts','Escalation messages'],['Deadline management','Exception escalation','Review coordination','Compliance operating visibility']),
};

export const phase2Regulations:Record<string,SeoEntry> = {
  'espr-digital-product-passport': {
    title:'EU Digital Product Passport and ESPR Supplier Data Guide',
    description:'Prepare supplier, product, material and evidence data for Digital Product Passport workflows under the EU Ecodesign for Sustainable Products Regulation.',
    h1:'Digital Product Passport Supplier Data Infrastructure',
    intro:'The EU Digital Product Passport is becoming an operational product-data requirement. Emissa can organize the supplier, material, product and evidence records that product-specific DPP obligations will consume.',
    keywords:['digital product passport software','DPP supplier data','ESPR compliance software','digital product passport supplier compliance'],
    sections:[
      {title:'The DPP infrastructure is now operational',body:'The European Commission launched the Digital Product Passport Registry and testing environment in July 2026. The Registry indexes unique product identifiers and registration metadata while detailed product data remains decentralized under the responsibility of economic operators.'},
      {title:'Do not build a passport as a one-off document',body:'A scalable DPP program starts with reusable supplier, product, material, facility and evidence records. Product passports can then be generated from controlled source data rather than manually assembled for every product family.'},
      {title:'Registration and traceability',body:'Before an in-scope product can be placed on the EU market under applicable DPP legislation, the relevant economic operator must register the DPP in the EU Registry. Internal systems therefore need clear identifier, version and source-data controls.'},
      {title:'Emissa operating model',body:'Emissa can connect product and supplier records to declarations, material evidence, owners, approvals and review history so DPP preparation sits inside the same supplier compliance architecture used for other requirements.'},
    ],
    faq:[['Is the EU DPP Registry live?','Yes. The European Commission announced that the Registry became operational on 20 July 2026.'],['Are all products already required to have a DPP?','No. Product-specific requirements and effective dates depend on the applicable legislation and delegated acts.'],['Does Emissa replace the EU DPP Registry?','No. Emissa organizes enterprise source data and workflow; official registration occurs through the required EU infrastructure.']],
    sources:[{label:'European Commission — Digital Product Passport Registry',url:'https://single-market-economy.ec.europa.eu/single-market/digital-product-passport/dpp-registry_en'},{label:'European Commission — DPP timeline',url:'https://single-market-economy.ec.europa.eu/single-market/digital-product-passport_en'}],
    note:'DPP obligations are product-specific. Confirm current delegated acts, scope and effective dates before making compliance decisions.',
  },
  'eu-battery-passport': {
    title:'EU Battery Passport Compliance and Supplier Data Guide',
    description:'Organize battery model, supplier, composition, performance and evidence data for EU battery passport requirements.',
    h1:'EU Battery Passport Data and Evidence Management',
    intro:'Battery passports require structured product information, controlled updates and clear responsibility across the battery lifecycle. Emissa can organize upstream evidence and product records before they are published through the required passport infrastructure.',
    keywords:['EU battery passport software','battery passport supplier data','battery regulation compliance software','digital battery passport'],
    sections:[
      {title:'18 February 2027 milestone',body:'Under Article 77 of Regulation (EU) 2023/1542, battery passports are required from 18 February 2027 for LMT batteries, industrial batteries above 2 kWh and electric-vehicle batteries placed on the market or put into service.'},
      {title:'Model and individual battery information',body:'The Regulation separates information about the battery model from information specific to the individual battery and establishes different access levels for the public, authorities and parties with a legitimate interest.'},
      {title:'Accuracy and lifecycle updates',body:'The economic operator placing the battery on the market is responsible for ensuring passport information is accurate, complete and current, subject to the transfer-of-responsibility rules in the Regulation.'},
      {title:'Supplier evidence layer',body:'Emissa can connect battery records to supplier composition data, declarations, product evidence, ownership and approvals so passport outputs can be traced back to reviewed source information.'},
    ],
    faq:[['When does the EU battery passport requirement begin?','Article 77 sets 18 February 2027 for the battery categories specified in the Regulation.'],['Which battery categories are included?','LMT batteries, industrial batteries above 2 kWh and electric-vehicle batteries are identified in Article 77.'],['Does Emissa host the legally required battery passport by itself?','Emissa can manage source data and workflow; the customer must ensure the final passport and registration architecture meets the applicable EU requirements.']],
    sources:[{label:'EUR-Lex — Regulation (EU) 2023/1542 Article 77',url:'https://eur-lex.europa.eu/eli/reg/2023/1542/2023-07-28'},{label:'European Commission — DPP Registry',url:'https://single-market-economy.ec.europa.eu/single-market/digital-product-passport/dpp-registry_en'}],
  },
  eudr: {
    title:'EUDR Supplier Due Diligence and Traceability Software Guide',
    description:'Structure supplier, commodity, geolocation, due-diligence and evidence workflows for the EU Deforestation Regulation.',
    h1:'EUDR Supplier Due Diligence and Evidence Infrastructure',
    intro:'EUDR readiness depends on traceable supplier, commodity, production-origin and due-diligence records. Emissa can organize the enterprise evidence layer around the EU Information System and customer obligations.',
    keywords:['EUDR compliance software','EUDR supplier due diligence','deforestation regulation supplier data','EUDR traceability'],
    sections:[
      {title:'Current application dates',body:'The European Commission states that EUDR applies from 30 December 2026 for large and medium operators and from 30 June 2027 for micro and small operators, with specified treatment for small operators previously covered by the EU Timber Regulation.'},
      {title:'Traceability before declaration',body:'Operators and traders need evidence that relevant products meet the Regulation. The internal data problem is connecting product and commodity records to suppliers, origin information, due-diligence decisions and the evidence behind them.'},
      {title:'Information System integration layer',body:'The Commission adopted technical rules for the EUDR Information System in July 2026 and continues to provide API and implementation documentation. Enterprise systems should retain the identifiers and evidence needed to reconcile internal records with submitted due-diligence statements.'},
      {title:'Emissa operating model',body:'Emissa can map suppliers, products, origin evidence, review status and approvals into controlled workflows so teams can identify missing evidence before submission or buyer response.'},
    ],
    faq:[['When does EUDR apply to large and medium operators?','The Commission currently states 30 December 2026.'],['When does it apply to micro and small operators?','The Commission currently states 30 June 2027, subject to the specific rules published by the EU.'],['Does Emissa submit EUDR due-diligence statements automatically?','This page describes the internal supplier-data and evidence layer. Any production submission integration must be configured against the current EU Information System specifications.']],
    sources:[{label:'European Commission — EUDR overview and application dates',url:'https://environment.ec.europa.eu/topics/forests/deforestation/regulation-deforestation-free-products_en'},{label:'European Commission — 2026 EUDR implementation update',url:'https://environment.ec.europa.eu/news/commission-updates-product-scope-and-tools-support-eudr-2026-07-13_en'}],
  },
  csddd: {
    title:'CSDDD Supplier Due Diligence Software and Evidence Guide',
    description:'Operationalize supplier human-rights and environmental due diligence evidence for the EU Corporate Sustainability Due Diligence Directive.',
    h1:'CSDDD Supplier Due Diligence Infrastructure',
    intro:'CSDDD turns value-chain due diligence into an operating process that requires ownership, evidence, risk assessment and remediation. Emissa can provide the supplier compliance layer around those activities.',
    keywords:['CSDDD supplier due diligence software','corporate sustainability due diligence software','CSDDD supplier compliance','EU due diligence platform'],
    sections:[
      {title:'Current EU timeline',body:'The European Commission states that, following the 2026 amendment, Member States must transpose the Directive by 26 July 2028 and it begins applying to companies that meet the defined conditions and thresholds from 26 July 2029.'},
      {title:'Due diligence needs operational evidence',body:'Policy statements are not enough. Teams need supplier records, risk findings, requests, mitigation actions, approvals, complaints or escalations and evidence showing what was reviewed and when.'},
      {title:'Prioritize by risk and relationship',body:'A useful system segments suppliers and business relationships so deeper review and remediation can be focused where the company’s process determines it is needed.'},
      {title:'Emissa operating model',body:'Supplier 360, Evidence Vault, workflows, CAPA and risk views can be used as the operating layer for organization-defined due-diligence procedures while preserving a reusable audit trail.'},
    ],
    faq:[['When does the amended CSDDD begin applying?','The European Commission currently states 26 July 2029 for companies meeting the applicable conditions and thresholds.'],['Does CSDDD apply to every company?','No. Scope and thresholds are defined in the Directive and should be checked against current official guidance.'],['Does Emissa provide legal determinations?','No. Emissa manages supplier data, evidence and workflow around the organization’s due-diligence program.']],
    sources:[{label:'European Commission — Company law and CSDDD current timeline',url:'https://commission.europa.eu/topics/business-and-industry/doing-business-eu/company-law-and-corporate-governance_en'}],
    note:'CSDDD has been amended since adoption. Confirm current scope, thresholds and national transposition requirements before relying on any workflow decision.',
  },
  'eu-forced-labour': {
    title:'EU Forced Labour Regulation Supplier Traceability Guide',
    description:'Prepare supplier traceability, product and forced-labour due-diligence evidence for Regulation (EU) 2024/3015.',
    h1:'EU Forced Labour Product Compliance Infrastructure',
    intro:'The EU forced-labour product ban creates a cross-supply-chain traceability challenge. Emissa can help organize product, supplier, facility, sourcing and evidence records so teams can respond to investigations and internal risk findings with a documented chain of evidence.',
    keywords:['EU forced labour regulation software','forced labour supplier due diligence','forced labor product compliance','supplier traceability forced labour'],
    sections:[
      {title:'14 December 2027 application date',body:'Regulation (EU) 2024/3015 prohibits products made with forced labour from being placed or made available on the EU market or exported from it. Article 39 states that the Regulation applies from 14 December 2027, with specified provisions applying earlier.'},
      {title:'Product and supply-chain scope',body:'The Regulation covers products regardless of sector or origin and addresses forced labour used at stages of extraction, harvest, production, manufacture, working or processing.'},
      {title:'Evidence for a risk-based process',body:'Internal supplier systems should preserve sourcing relationships, manufacturing locations, product-component links, supplier responses, risk findings, remediation and the evidence supporting conclusions.'},
      {title:'Emissa operating model',body:'Emissa can connect due-diligence evidence, supplier risk, corrective actions and product relationships so responses are based on controlled records instead of reconstructed email threads.'},
    ],
    faq:[['When does the EU Forced Labour Regulation apply?','Article 39 states that it applies from 14 December 2027, while certain institutional provisions apply earlier.'],['Does the regulation cover imported and EU-made products?','Yes. It addresses products placed or made available on the EU market and products exported from the EU, regardless of origin.'],['Does Emissa decide whether forced labour occurred?','No. Emissa provides workflow, traceability and evidence infrastructure; factual and legal determinations remain with the responsible organization and authorities.']],
    sources:[{label:'EUR-Lex — Regulation (EU) 2024/3015',url:'https://eur-lex.europa.eu/eli/reg/2024/3015/oj/eng'}],
  },
  uflpa: {
    title:'UFLPA Supplier Traceability and Import Evidence Guide',
    description:'Organize supplier, manufacturing, sourcing and import evidence for UFLPA forced-labor compliance workflows.',
    h1:'UFLPA Supplier Traceability and Evidence Management',
    intro:'UFLPA enforcement makes upstream traceability commercially critical for U.S. importers and their suppliers. Emissa can organize supplier, facility, product and sourcing evidence so teams can identify gaps before a shipment becomes an enforcement problem.',
    keywords:['UFLPA compliance software','UFLPA supplier traceability','forced labor importer compliance','UFLPA evidence management'],
    sections:[
      {title:'Rebuttable presumption',body:'CBP explains that UFLPA creates a rebuttable presumption for goods mined, produced or manufactured wholly or in part in Xinjiang or by an entity on the UFLPA Entity List, subject to the statute and CBP implementation.'},
      {title:'Reasonable-care supply-chain records',body:'CBP advises importers to exercise reasonable care, understand where and how products are manufactured or produced, and maintain sufficient documentation to support admissibility decisions.'},
      {title:'Supplier evidence structure',body:'A controlled workflow can map products to suppliers, sub-tier facilities, sourcing regions, declarations, bills of material, transaction records and any supporting chain-of-custody evidence.'},
      {title:'Responding to exceptions',body:'If evidence is incomplete or inconsistent, the system should create targeted follow-up and remediation rather than marking the entire supplier record complete.'},
    ],
    faq:[['What is the UFLPA rebuttable presumption?','CBP describes a presumption affecting goods from Xinjiang or entities on the UFLPA Entity List, subject to the statutory framework.'],['What does CBP expect from importers?','CBP emphasizes reasonable care and understanding where and how products are manufactured or produced, supported by documentation.'],['Can Emissa guarantee admissibility?','No. Emissa organizes supplier and evidence records; CBP determines admissibility under U.S. law.']],
    sources:[{label:'CBP — UFLPA overview',url:'https://www.help.cbp.gov/s/article/Article1842'},{label:'CBP — Forced Labor FAQs',url:'https://www.cbp.gov/trade/forced-labor/frequently-asked-questions'}],
  },
  'conflict-minerals': {
    title:'SEC Conflict Minerals Supplier Data and CMRT Workflow Guide',
    description:'Structure 3TG supplier surveys, country-of-origin inquiries, smelter/refiner records and due-diligence evidence for conflict-minerals reporting.',
    h1:'Conflict Minerals Supplier Due Diligence Infrastructure',
    intro:'Conflict-minerals reporting depends on structured supplier inquiry and chain-of-custody evidence. Emissa can organize supplier responses, product scope, 3TG records, review findings and follow-up actions around the reporting process.',
    keywords:['conflict minerals compliance software','CMRT supplier management','3TG supplier due diligence','conflict minerals reporting workflow'],
    sections:[
      {title:'SEC reporting framework',body:'The SEC conflict-minerals rule applies to certain reporting issuers when conflict minerals are necessary to the functionality or production of products they manufacture or contract to manufacture, subject to the rule’s requirements and interpretations.'},
      {title:'Reasonable country-of-origin inquiry',body:'The SEC describes a good-faith reasonable country-of-origin inquiry as a key step in determining whether additional due diligence and reporting may be required.'},
      {title:'Supplier survey operations',body:'Teams often need to request and validate supplier data, record smelter or refiner information, identify missing responses, preserve review comments and track remediation or escalation.'},
      {title:'Emissa operating model',body:'Emissa can connect supplier questionnaires, evidence, products, findings and CAPA so conflict-minerals work remains traceable and reusable across responsible-sourcing workflows.'},
    ],
    faq:[['Which minerals are commonly referred to as 3TG?','Tin, tantalum, tungsten and gold are the conflict minerals addressed by the SEC rule.'],['What is a reasonable country-of-origin inquiry?','The SEC describes it as a good-faith inquiry reasonably designed to determine whether covered conflict minerals originated in the covered countries or came from recycled or scrap sources.'],['Does Emissa file Form SD?','Emissa can support internal supplier-data and evidence workflows; required SEC filings remain the issuer’s responsibility.']],
    sources:[{label:'SEC — Conflict Minerals final rule',url:'https://www.sec.gov/rules-regulations/2012/08/conflict-minerals'},{label:'SEC — Conflict Minerals Disclosure compliance guide',url:'https://www.sec.gov/resources-small-businesses/small-business-compliance-guides/conflict-minerals-disclosure'}],
  },
  'california-proposition-65': {
    title:'California Proposition 65 Supplier and Product Evidence Guide',
    description:'Organize supplier declarations, product chemical evidence, warning decisions and review history for California Proposition 65 workflows.',
    h1:'Proposition 65 Product and Supplier Evidence Management',
    intro:'Proposition 65 decisions often depend on product composition, exposure analysis, supplier declarations and warning controls. Emissa can organize those records so teams can show which evidence supported each product decision.',
    keywords:['Proposition 65 compliance software','Prop 65 supplier declarations','California product compliance software','Prop 65 evidence management'],
    sections:[
      {title:'Clear and reasonable warnings',body:'OEHHA explains that businesses subject to Proposition 65 must provide clear and reasonable warnings before knowingly and intentionally exposing people to listed chemicals unless an exemption or applicable exposure determination applies.'},
      {title:'Supplier and product data',body:'Product teams need a controlled link between finished products, components, supplier declarations, chemical information, testing or exposure analysis, reviewers and the warning decision.'},
      {title:'Warning rules evolve',body:'OEHHA amended short-form warning rules in December 2024 and maintains current regulations, chemical lists and safe-harbor information. Compliance records should therefore include the rule version and review date used for a decision.'},
      {title:'Emissa operating model',body:'Emissa can preserve supplier evidence, product relationships, approvals and review dates so warning decisions can be re-evaluated when ingredients, suppliers or regulations change.'},
    ],
    faq:[['What does Proposition 65 generally require?','OEHHA states that covered businesses must provide clear and reasonable warnings before certain exposures to listed chemicals unless an exemption applies.'],['Is the chemical list static?','No. OEHHA maintains and updates the Proposition 65 list.'],['Can Emissa determine whether a warning is legally required?','No. Emissa manages the evidence and workflow; exposure and legal determinations require appropriate expertise.']],
    sources:[{label:'OEHHA — Businesses and Proposition 65',url:'https://oehha.ca.gov/proposition-65/businesses-and-proposition-65'},{label:'OEHHA — Clear and Reasonable Warning amendments',url:'https://oehha.ca.gov/proposition-65/crnr/proposition-65-clear-and-reasonable-warnings-safe-harbor-methods-and-content'}],
  },
  'california-climate-disclosure': {
    title:'California SB 253 and SB 261 Supplier Data Workflow Guide',
    description:'Structure supplier, Scope 3 and climate-risk source data for California corporate climate disclosure programs.',
    h1:'California Climate Disclosure Supplier Data Infrastructure',
    intro:'California climate disclosure requirements increase the need for controlled Scope 1, 2 and 3 source data, especially supplier and value-chain information. Emissa can connect the supplier evidence layer to the organization’s reporting process.',
    keywords:['SB 253 software','California climate disclosure software','Scope 3 supplier data California','SB 261 compliance workflow'],
    sections:[
      {title:'CARB program development',body:'CARB is developing the corporate greenhouse-gas reporting program authorized by SB 253 and the climate-related financial-risk disclosure program authorized by SB 261, as amended by SB 219.'},
      {title:'Supplier data matters for Scope 3',body:'CARB describes SB 253 as requiring covered reporting entities to disclose Scope 1, 2 and 3 greenhouse-gas emissions. Supplier, purchasing, logistics and product data therefore become part of the reporting evidence architecture.'},
      {title:'Preserve methodology and source records',body:'A defensible process should keep reporting-period data, calculation methodology, source-system references, supplier-specific inputs, assumptions, approvals and version history together.'},
      {title:'Emissa operating model',body:'Emissa can structure supplier and purchasing evidence used in Scope 3 workflows while connecting that same data to buyer requests, product footprints and other supplier compliance requirements.'},
    ],
    faq:[['What California programs are covered here?','CARB identifies SB 253 corporate GHG reporting and SB 261 climate-related financial-risk disclosure programs, as amended by SB 219.'],['Why is supplier data important?','Scope 3 reporting can depend heavily on value-chain, purchasing and supplier information.'],['Does Emissa replace CARB reporting systems or assurance providers?','No. Emissa supports source-data and evidence workflow around the organization’s reporting process.']],
    sources:[{label:'California Air Resources Board — Corporate climate disclosure programs',url:'https://ww2.arb.ca.gov/our-work/programs/california-corporate-greenhouse-gas-reporting-and-climate-related-financial-risk'}],
  },
};
