import type { SeoEntry } from './seoExpansionContent';

const entry=(title:string,description:string,intro:string,keywords:string[],bullets:string[],source:{label:string;url:string}):SeoEntry=>({
  title,description,h1:title,intro,keywords,
  sections:[
    {title:'Build the applicability record first',body:'Start with the product, market, supplier and regulatory scope that determine whether the requirement belongs in the operating workflow.'},
    {title:'Preserve the source data',body:'A defensible compliance workflow keeps the source records, methodology, ownership, review state and effective period behind every value or declaration.',bullets},
    {title:'Reuse approved records',body:'When the same supplier, product, facility or material evidence supports multiple requests, reuse should preserve scope and approval history rather than copying an untraceable answer.'},
    {title:'Emissa operating model',body:'Emissa can connect the requirement to suppliers, products, evidence, owners, deadlines, approvals and external reporting identifiers while leaving official filings in the systems required by the regulator.'},
  ],
  faq:[['Does this page determine legal applicability?','No. Applicability should be confirmed against current official guidance and qualified professional advice.'],['Can one supplier record support multiple workflows?','Yes, when the evidence is current and correctly scoped; Emissa is designed to preserve those relationships explicitly.'],['Does Emissa replace the regulator portal?','No. Emissa manages the internal supplier compliance data and workflow around required external processes.']],
  sources:[source],note:'Regulatory scope and implementation details can change. Verify current official guidance before relying on a deadline or filing decision.'
});

const eudrSource={label:'European Commission — EUDR',url:'https://environment.ec.europa.eu/topics/forests/deforestation/regulation-deforestation-free-products_en'};
const cbamSource={label:'European Commission — CBAM definitive regime',url:'https://taxation-customs.ec.europa.eu/carbon-border-adjustment-mechanism/cbam-definitive-regime_en'};

export const phase3MoreRegulations:Record<string,SeoEntry>={
  'epr-eu-packaging':entry('EU Packaging and Packaging Waste Compliance Guide','Supplier, product and packaging data guidance for EU packaging and producer-responsibility workflows.','EU packaging compliance increasingly depends on controlled product, material, weight, market and producer records. Emissa can organize the reusable data and evidence layer around those requirements.',['EU packaging compliance software','PPWR supplier data','EU packaging EPR'],['Packaging component and material','Weight and format','Product and market relationship','Producer/economic operator context','Supplier specification evidence','Review and effective period'],{label:'European Commission — Packaging waste',url:'https://environment.ec.europa.eu/topics/waste-and-recycling/packaging-waste_en'}),
  'epr-germany':entry('Germany Packaging Act and LUCID Data Guide','Operational supplier and packaging data guidance for German packaging registration and producer-responsibility workflows.','German packaging compliance requires organizations to maintain consistent producer, brand, packaging and market records around the official LUCID and system-participation processes where applicable. Emissa can preserve the internal evidence layer.',['Germany packaging act software','LUCID packaging compliance','VerpackG supplier data'],['Producer and brand identity','Packaging type and quantity','Product relationship','Market/effective period','System participation evidence','Registration and reporting references'],{label:'Central Agency Packaging Register — LUCID / Packaging Act',url:'https://www.verpackungsregister.org/en/'}),
  'epr-france':entry('France Packaging EPR Supplier Data Guide','Product, packaging, market and producer data guidance for French extended producer responsibility workflows.','French EPR programs require reliable product and material data and can involve category-specific producer responsibility organizations. Emissa can organize the internal product, supplier and evidence records that support those external processes.',['France packaging EPR software','French REP compliance','France producer responsibility data'],['Producer/entity identity','Product and packaging category','Material and quantity','Market/reporting period','Supporting supplier evidence','External registration or declaration reference'],{label:'ADEME — Filières à responsabilité élargie du producteur',url:'https://filieres-rep.ademe.fr/'}),
  'cbam-cement':entry('CBAM Cement Supplier Data Guide','Product, installation and embedded-emissions evidence guidance for cement products potentially within CBAM scope.','Cement CBAM workflows should connect customs scope to production installations, production quantities, emissions methodology and source evidence. Emissa can preserve those relationships across importer requests.',['CBAM cement software','cement embedded emissions','CBAM cement supplier data'],['Product and CN context','Production installation','Reporting period','Production quantity','Direct emissions inputs','Methodology and source evidence'],cbamSource),
  'cbam-fertilizers':entry('CBAM Fertiliser Supplier Data Guide','Supplier, installation and embedded-emissions evidence guidance for fertiliser products potentially covered by CBAM.','Fertiliser CBAM requests can depend on product classification, installation context, production data and emissions evidence. Emissa can structure those records so approved information is reusable and versioned.',['CBAM fertilizer software','fertiliser embedded emissions','CBAM supplier data fertilizers'],['Product/customs context','Installation and process data','Production quantity','Emissions inputs','Methodology version','Released importer response package'],cbamSource),
  'eudr-rubber':entry('EUDR Rubber Supplier Traceability Guide','Supplier, origin and due-diligence evidence guidance for rubber supply chains under EUDR.','Rubber EUDR readiness depends on connecting supplier and intermediary records to production-origin evidence, risk review and the affected products. Emissa can maintain that traceability graph.',['EUDR rubber compliance','rubber supplier traceability','deforestation due diligence rubber'],['Supplier/intermediary','Commodity/product','Production origin','Geolocation/source evidence','Risk assessment','Mitigation and approval'],eudrSource),
  'eudr-timber':entry('EUDR Timber Supplier Traceability Guide','Supplier, origin and due-diligence evidence guidance for timber and wood supply chains under EUDR.','Timber and wood workflows need traceable origin, supplier, product and due-diligence records. Emissa can connect source evidence and risk decisions to the products and external statements they support.',['EUDR timber compliance','wood supplier traceability','deforestation due diligence timber'],['Supplier and chain-of-custody context','Commodity/product','Production origin','Geolocation/source evidence','Risk findings','Due-diligence approval'],eudrSource),
  'eudr-soy':entry('EUDR Soy Supplier Traceability Guide','Supplier, production-origin and due-diligence evidence guidance for soy supply chains under EUDR.','Soy EUDR readiness requires reliable supplier, origin and evidence relationships before risk assessment and external due-diligence statements. Emissa can structure that internal operating layer.',['EUDR soy compliance','soy traceability software','deforestation due diligence soy'],['Supplier/intermediary','Commodity/product','Production origin','Location evidence','Risk review','Mitigation/approval history'],eudrSource),
  'eudr-cattle':entry('EUDR Cattle Supplier Traceability Guide','Supplier, origin and due-diligence evidence guidance for cattle-related supply chains under EUDR.','Cattle-related EUDR workflows require product-scope and origin records that remain traceable through supplier relationships, evidence review and risk decisions. Emissa can preserve those links.',['EUDR cattle compliance','cattle traceability EUDR','deforestation due diligence cattle'],['Supplier/intermediary','Relevant product scope','Production origin','Traceability evidence','Risk assessment','Decision and mitigation history'],eudrSource),
};
