import type { Metadata } from 'next';
import '../../seo.css';

export const metadata:Metadata={title:'Emissa Editorial and Regulatory Content Policy',description:'How Emissa sources, reviews, dates and corrects public supplier compliance and regulatory guidance.',alternates:{canonical:'/about/editorial-policy'},keywords:['Emissa editorial policy','supplier compliance regulatory sources','regulatory content methodology']};

const standards=[
  ['Primary sources first','Regulatory pages prioritize official regulator, government, statute, agency and standards-body sources over summaries from third parties.'],
  ['Operational, not legal advice','Emissa content explains data, evidence and workflow implications. It does not replace legal advice, customs classification, regulatory applicability analysis or professional certification.'],
  ['Visible review dates','High-change regulatory pages can display a last-reviewed date, current operating status and a next milestone or monitoring note.'],
  ['Source-linked claims','Material regulatory dates and program-status statements should be tied to an authoritative source that readers can open and verify.'],
  ['No invented benchmarks','Research findings are not published until the underlying production dataset supports a consistent, privacy-protected aggregate result.'],
  ['Corrections and versioning','When official guidance changes, Emissa updates the affected public content and should preserve internal review history for material methodology changes.'],
] as const;

export default function EditorialPolicy(){return <main className="seoPage"><nav className="seoNav"><a className="seoBrand" href="/">EMISSA</a><div><a href="/regulations">Regulations</a><a href="/research">Research</a><a href="/regulatory-calendar">Calendar</a><a href="/demo">Demo</a></div></nav><article><header className="seoHero compact"><span className="seoKicker">Trust & Methodology</span><h1>Editorial and Regulatory Content Policy</h1><p>Emissa publishes supplier compliance content to help operators structure data, evidence and workflows. This policy explains how public regulatory content is sourced and where its limits are.</p></header><section className="seoGrid three">{standards.map(([title,body])=><article className="seoCard" key={title}><h2>{title}</h2><p>{body}</p></article>)}</section><section className="seoSection"><h2>Regulatory page review standard</h2><p>When a page covers an active or upcoming regulatory program, Emissa aims to identify official source material, separate current facts from implementation guidance, state uncertainty where dates or rulemaking are still evolving, and avoid representing workflow software as a legal determination.</p></section><section className="seoSection"><h2>Research standard</h2><p>Public benchmark methodology is documented before findings are published. Demo, synthetic and test records are excluded from production benchmarks, and aggregate cohorts should be large enough that customer- or supplier-level information cannot be inferred.</p><div className="seoActions"><a className="seoSecondary" href="/research/methodology">Benchmark methodology</a><a className="seoSecondary" href="/research/state-of-supplier-compliance">State of Supplier Compliance framework</a></div></section><section className="seoCta"><h2>Use the regulatory library as a starting point, then verify the source.</h2><p>Each high-change regulatory page is designed to link back to official guidance.</p><a className="seoPrimary" href="/regulations">Browse regulatory intelligence</a></section></article></main>;}
