import type { Metadata } from 'next';
import '../seo.css';

export const metadata:Metadata={title:'US Packaging EPR State Tracker 2026',description:'Track current packaging extended producer responsibility programs and implementation status in California, Colorado, Oregon, Maine, Minnesota and Maryland.',alternates:{canonical:'/epr-state-tracker'},keywords:['US packaging EPR states','packaging EPR state tracker','California Oregon Colorado Maine Minnesota Maryland EPR']};

const states=[
  {state:'California',law:'SB 54',status:'Active regulations',detail:'Permanent regulations became effective May 1, 2026. CalRecycle identifies Circular Action Alliance as the first approved PRO.',href:'/regulations/epr-california',source:'https://calrecycle.ca.gov/packaging/packaging-epr/'},
  {state:'Oregon',law:'Recycling Modernization Act',status:'Program operating',detail:'Oregon DEQ states program changes began in July 2025; covered producers generally register, report and pay through an approved PRO unless exempt.',href:'/regulations/epr-oregon',source:'https://www.oregon.gov/deq/recycling/pages/modernizing-oregons-recycling-system.aspx'},
  {state:'Maine',law:'Stewardship Program for Packaging',status:'Implementing',detail:'Maine DEP is working through Stewardship Organization selection and says a revised implementation schedule will follow.',href:'/regulations/epr-maine',source:'https://www.maine.gov/dep/waste/recycle/epr.html'},
  {state:'Minnesota',law:'Packaging Waste and Cost Reduction Act',status:'Implementing',detail:'MPCA is building the statewide program through rulemaking, needs assessment and stewardship planning.',href:'/regulations/epr-minnesota',source:'https://www.pca.state.mn.us/air-water-land-climate/extended-producer-responsibility-for-packaging'},
  {state:'Maryland',law:'Packaging and Paper Products — Producer Responsibility Plans Act',status:'Active regulations',detail:'MDE states implementing regulations became effective May 25, 2026 and identifies Circular Action Alliance as the approved PRO.',href:'/regulations/epr-maryland',source:'https://mde.maryland.gov/programs/land/WasteManagement/Pages/ProducerResponsibility.aspx'},
  {state:'Colorado',law:'HB 22-1355',status:'Implementing',detail:'Colorado CDPHE describes a statewide producer-responsibility program for packaging, paper products and food service ware.',href:'/regulations/epr-colorado',source:'https://cdphe.colorado.gov/hm/recycling'},
] as const;

export default function EprStateTracker(){const schema={'@context':'https://schema.org','@type':'ItemList',name:'US Packaging EPR State Tracker',itemListElement:states.map((item,index)=>({'@type':'ListItem',position:index+1,name:`${item.state} ${item.law}`,url:`https://emissa.tech${item.href}`}))};return <main className="seoPage"><nav className="seoNav"><a className="seoBrand" href="/">EMISSA</a><div><a href="/regulations">Regulations</a><a href="/regulatory-calendar">Calendar</a><a href="/tools">Tools</a><a href="/research">Research</a><a href="/demo">Demo</a></div></nav><header className="seoHero compact"><span className="seoKicker">Last reviewed • August 22, 2026</span><h1>US Packaging EPR State Tracker</h1><p>A source-linked operating reference for major state packaging producer-responsibility programs currently covered by the Emissa regulatory library. Status labels summarize implementation—not legal applicability.</p></header><section className="seoGrid three">{states.map(item=><article className="seoCard" key={item.state}><span className="seoKicker">{item.status}</span><h2>{item.state}</h2><h3>{item.law}</h3><p>{item.detail}</p><div className="seoActions"><a className="seoPrimary" href={item.href}>Operational guide</a><a className="seoSecondary" href={item.source} target="_blank" rel="noreferrer">Official source ↗</a></div></article>)}</section><section className="seoSection"><h2>What a producer should centralize before reporting.</h2><div className="seoGrid three"><article className="seoCard"><h3>Packaging master</h3><p>Product, component, material, weight, format, supplier and market relationships.</p></article><article className="seoCard"><h3>Producer status</h3><p>Entity, brand, exemption or exclusion basis, PRO relationship and effective period.</p></article><article className="seoCard"><h3>Source evidence</h3><p>Supplier specifications, calculation inputs, review history and the exact values released externally.</p></article></div></section><section className="seoCta"><h2>Run state EPR from one packaging data layer.</h2><p>Emissa is designed to separate reusable product and packaging data from changing jurisdiction requirements.</p><a className="seoPrimary" href="/demo">See the EPR operating model</a></section><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></main>;}
