import LegalPage from '@/components/LegalPage';
import '../marketing.css';

export default function TermsPage(){return <LegalPage title="Terms of Service" subtitle="These terms govern access to and use of Emissa.tech and the Emissa software platform.">
<h2>1. Agreement</h2><p>By accessing or using Emissa, you agree to these Terms of Service and any order form, subscription agreement, or other written agreement that references them. If you use Emissa on behalf of an organization, you represent that you have authority to bind that organization.</p>
<h2>2. Service</h2><p>Emissa provides supplier compliance infrastructure, workflow, reporting, data-management, analytics, integration, and related software services. Features may evolve over time. Unless expressly stated in a signed agreement, Emissa does not provide legal, tax, accounting, engineering, certification, or regulatory advice.</p>
<h2>3. Accounts and access</h2><p>You are responsible for maintaining accurate account information, safeguarding credentials, and limiting access to authorized users. You are responsible for activity performed through your account except to the extent caused by Emissa's breach of its obligations.</p>
<h2>4. Customer data</h2><p>You retain ownership of data submitted to the service. You grant Emissa the rights reasonably necessary to host, process, transmit, back up, secure, analyze, and display that data to provide and improve the service. You are responsible for having the rights and permissions necessary to submit customer, supplier, employee, and other third-party data.</p>
<h2>5. Compliance outputs</h2><p>Emissa may help organize evidence, calculate values, prepare reports, monitor deadlines, and generate workflow outputs. You remain responsible for reviewing submissions, determining legal applicability, validating source data, and obtaining professional advice when required.</p>
<h2>6. Fees and billing</h2><p>Subscription fees, billing frequency, included usage, implementation services, and renewal terms are stated in the applicable order or checkout flow. Unless otherwise stated, fees are non-refundable except where required by law or expressly agreed in writing.</p>
<h2>7. Acceptable use</h2><p>You may not misuse the service, interfere with its operation, attempt unauthorized access, introduce malicious code, use the platform to violate law or third-party rights, or reverse engineer the service except where such restriction is prohibited by law. The Acceptable Use Policy is incorporated into these terms.</p>
<h2>8. Third-party services</h2><p>Integrations and external services may be provided by third parties and may be subject to separate terms. Emissa is not responsible for third-party services outside its control.</p>
<h2>9. Confidentiality</h2><p>Each party will protect the other party's non-public confidential information using reasonable care and will use it only for purposes of the business relationship, subject to customary exceptions for information that is public, independently developed, lawfully received, or required to be disclosed by law.</p>
<h2>10. Intellectual property</h2><p>Emissa and its licensors retain all rights in the service, software, designs, documentation, models, workflows, and other platform technology. No rights are granted except the limited right to use the service during an active subscription.</p>
<h2>11. Disclaimers</h2><p>The service is provided on an “as available” basis. To the maximum extent permitted by law, Emissa disclaims implied warranties of merchantability, fitness for a particular purpose, and non-infringement. Regulatory requirements change, and no software can guarantee compliance or acceptance by a regulator, buyer, auditor, or other third party.</p>
<h2>12. Limitation of liability</h2><p>To the maximum extent permitted by law and except for liabilities that cannot legally be limited, neither party will be liable for indirect, incidental, special, consequential, exemplary, or punitive damages or lost profits, revenues, goodwill, or data. Any negotiated liability cap in an order form or signed agreement controls over this section.</p>
<h2>13. Suspension and termination</h2><p>Emissa may suspend access for material security risk, unlawful use, non-payment, or material breach. Upon termination, access ends and data will be handled according to the applicable agreement, privacy policy, and retention practices.</p>
<h2>14. Changes</h2><p>We may update these terms from time to time. Material changes will be posted with an updated effective date and, where appropriate, additional notice.</p>
<h2>15. Contact</h2><p>Questions about these terms may be submitted through Emissa.tech's contact channels.</p>
</LegalPage>}
