import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { productVideos } from '@/lib/videoLibrary';
import '../../seo.css';

type Slug=keyof typeof productVideos;
export function generateStaticParams(){return Object.keys(productVideos).map(slug=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const video=productVideos[slug as Slug];if(!video)return{};return{title:video.title,description:video.description,alternates:{canonical:`/videos/${slug}`},robots:{index:true,follow:true}};}
export default async function VideoPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const video=productVideos[slug as Slug];if(!video)notFound();const schema={'@context':'https://schema.org','@type':'VideoObject',name:video.title,description:video.description,thumbnailUrl:[video.thumbnailUrl],uploadDate:video.uploadDate,embedUrl:video.embedUrl,duration:video.duration};return <main className="seoPage"><nav className="seoNav"><a className="seoBrand" href="/">EMISSA</a><div><a href="/videos">Videos</a><a href="/platform">Platform</a><a href="/docs">Docs</a><a href="/demo">Demo</a></div></nav><article><header className="seoHero compact"><span className="seoKicker">Product Video</span><h1>{video.title}</h1><p>{video.description}</p></header><section className="seoSection"><div style={{aspectRatio:'16/9',width:'100%'}}><iframe title={video.title} src={video.embedUrl} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen style={{width:'100%',height:'100%',border:0}}/></div></section><section className="seoSection"><h2>Transcript</h2>{video.transcript.map((p,i)=><p key={i}>{p}</p>)}</section><section className="seoSection"><h2>Related workflows</h2><div className="seoActions">{video.related.map(item=><a className="seoSecondary" href={item.href} key={item.href}>{item.label}</a>)}</div></section></article><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></main>;}
