import { comparisons, docs, personas, templates, tools } from '@/lib/seoExpansionContent';
import { phase3Comparisons } from '@/lib/seoExpansionPhase3Comparisons';
import { phase3Templates, phase3Tools } from '@/lib/seoExpansionPhase3';
import { allBlogTopicPosts, blogCategories } from '@/lib/blogCatalog';
import { sitemapResponse } from '@/lib/sitemapXml';

export const dynamic='force-static';
const allComparisons={...comparisons,...phase3Comparisons};const allTemplates={...templates,...phase3Templates};const allTools={...tools,...phase3Tools};
const blogSlugs=['what-is-supplier-compliance-infrastructure','supplier-compliance-software-vs-esg-software','supplier-compliance-checklist','how-to-manage-buyer-compliance-requests','supplier-due-diligence-workflow','supplier-certificate-management-guide','scope-3-as-supplier-data-foundation','cbam-supplier-data-checklist','epr-packaging-compliance-workflow','product-carbon-footprint-vs-scope-3','supplier-onboarding-compliance-process','supplier-questionnaire-management','supplier-compliance-kpis','how-to-build-supplier-compliance-system-of-record','supplier-compliance-platform-buyers-guide'];
export function GET(){return sitemapResponse(['/resources','/blog','/for','/compare','/tools','/templates','/docs','/research','/research/methodology','/research/state-of-supplier-compliance','/research/supplier-compliance-maturity-model','/regulatory-calendar','/epr-state-tracker','/resources/supplier-compliance-guide','/resources/scope-3-supplier-data-guide','/resources/cbam-supplier-guide','/resources/epr-compliance-guide',...Object.keys(personas).map(slug=>`/for/${slug}`),...Object.keys(allComparisons).map(slug=>`/compare/${slug}`),...Object.keys(allTools).map(slug=>`/tools/${slug}`),...Object.keys(allTemplates).map(slug=>`/templates/${slug}`),...Object.keys(docs).map(slug=>`/docs/${slug}`),...Object.keys(blogCategories).map(slug=>`/blog/category/${slug}`),...blogSlugs.map(slug=>`/blog/${slug}`),...Object.keys(allBlogTopicPosts).map(slug=>`/blog/topics/${slug}`)]);}
