import { sitemapResponse } from '@/lib/sitemapXml';

export const dynamic='force-static';

const paths=[
  '/',
  '/platform',
  '/software',
  '/product-compliance',
  '/solutions',
  '/solutions/supplier-compliance-infrastructure',
  '/solutions/supplier-due-diligence',
  '/solutions/buyer-compliance-requests',
  '/solutions/supplier-evidence-management',
  '/solutions/compliance-data-rooms',
  '/solutions/supplier-certificate-management',
  '/solutions/supplier-onboarding-compliance',
  '/solutions/supplier-questionnaire-management',
  '/solutions/ecovadis-readiness',
  '/solutions/scope-3-supplier-data',
  '/solutions/epr-compliance',
  '/solutions/cbam-compliance',
  '/solutions/product-carbon-footprints',
  '/solutions/climate-risk',
  '/industries',
  '/industries/manufacturing-supplier-compliance',
  '/industries/automotive-supplier-compliance',
  '/industries/industrial-supplier-compliance',
  '/industries/packaging-epr-compliance',
  '/industries/metals-cbam-compliance',
  '/regulations',
  '/regulatory-calendar',
  '/integrations',
  '/compare',
  '/tools',
  '/templates',
  '/research',
  '/research/state-of-supplier-compliance',
  '/research/methodology',
  '/security',
  '/about/editorial-policy',
  '/pricing',
  '/demo',
];

export function GET(){return sitemapResponse(paths);}
