import type { Metadata } from 'next';
import '../../seo.css';

export const metadata:Metadata={title:'Supplier Compliance Maturity Model',description:'A five-level operating maturity model for supplier evidence, requirements, ownership, workflow automation, auditability and data reuse.',alternates:{canonical:'/research/supplier-compliance-maturity-model'},keywords:['supplier compliance maturity model','supplier compliance maturity levels','supplier compliance framework']};

const levels=[
  ['Level 1 — Reactive','Requirements and evidence are reconstructed from email, spreadsheets and folders after a request or audit appears.','Centralize supplier and requirement ownership.'],
  ['Level 2 — Structured','Core supplier records and checklists exist, but evidence review, expirations and cross-team ownership still depend on manual follow-up.','Link evidence to requirements and automate timing controls.'],
  ['Level 3 — Controlled','Requirements, evidence, review states, owners and exceptions are visible in a shared operating model with reliable audit history.','Standardize approvals and remediation across workflows.'],
  ['Level 4 — Automated','Reminders, routing, supplier requests, risk signals and recurring evidence workflows are automated using controlled source records.','Integrate source systems and expand reusable structured data.'],
  ['Level 5 — Compliance Infrastructure','Supplier, facility, product, requirement and evidence data is reusable across buyer, regulatory, product, trade and sustainability workflows.','Optimize network-level risk, benchmarking and continuous regulatory change management.'],
] as const;

export default function MaturityModel(){return <main className="seoPage"><nav className="seoNav"><a className="seoBrand" href="/">EMISSA</a><div><a href="/research">Research</a><a href="/tools/supplier-compliance-maturity-assessment">Assessment</a><a href="/platform">Platform</a><a href="/demo">Demo</a></div></nav><article><header className="seoHero compact"><span className="seoKicker">Emissa Research Framework</span><h1>Supplier Compliance Maturity Model</h1><p>A practical five-level model for evaluating whether supplier compliance is reactive administration or durable enterprise infrastructure.</p><div className="seoActions"><a className="seoPrimary" href="/tools/supplier-compliance-maturity-assessment">Score your current model</a><a className="seoSecondary" href="/research/methodology">Research methodology</a></div></header><section className="seoGrid">{levels.map(([level,body,next])=><article className="seoCard" key={level}><span className="seoKicker">Maturity Level</span><h2>{level}</h2><p>{body}</p><h3>Priority to advance</h3><p>{next}</p></article>)}</section><section className="seoSection"><h2>What changes between levels.</h2><div className="seoGrid three"><article className="seoCard"><h3>Evidence</h3><p>Files become scoped, approved, current evidence tied to explicit requirements.</p></article><article className="seoCard"><h3>Workflow</h3><p>Reminders and ad-hoc follow-up become assigned work, approvals, escalation and corrective action.</p></article><article className="seoCard"><h3>Data reuse</h3><p>Repeated supplier requests become reusable structured records across regulatory, buyer and product workflows.</p></article></div></section><section className="seoCta"><h2>Move one maturity level at a time.</h2><p>Emissa is designed to provide the supplier, evidence, workflow and audit controls behind the model.</p><a className="seoPrimary" href="/demo">See the operating model</a></section></article></main>;}
