import LegalPage from '@/components/LegalPage';
import '../marketing.css';

export default function PrivacyPage(){return <LegalPage title="Privacy Policy" subtitle="How Emissa collects, uses, discloses, and protects personal information.">
<h2>1. Information we collect</h2><p>We may collect account and contact information, business profile information, billing and subscription details, support communications, lead-form submissions, user-generated content, supplier and compliance data submitted to the platform, device and browser information, IP address, log data, and usage analytics.</p>
<h2>2. How we collect information</h2><p>Information may be provided directly by you, submitted by your organization or authorized users, received through configured integrations, generated through your use of the service, or provided by service providers that support hosting, payments, analytics, authentication, communications, and security.</p>
<h2>3. How we use information</h2><p>We use information to provide, secure, maintain, support, personalize, and improve Emissa; authenticate users; process payments; respond to requests; operate integrations; generate requested workflows and reports; detect abuse; communicate service information; analyze product usage; and comply with legal obligations.</p>
<h2>4. Business and supplier data</h2><p>Customer organizations may submit business records, supplier records, product information, evidence documents, emissions data, packaging data, shipment data, and other compliance-related information. Emissa processes this information to provide the contracted service and does not claim ownership of customer data.</p>
<h2>5. Disclosure of information</h2><p>We may disclose information to service providers and subprocessors that help operate the service, to integrated third-party services at your direction, to professional advisers, in connection with a corporate transaction, or where required to comply with law, protect rights, prevent fraud, or secure the service. We do not state that we sell personal information for monetary consideration.</p>
<h2>6. Cookies and analytics</h2><p>We may use cookies and similar technologies for authentication, preferences, security, site functionality, analytics, and performance. Additional information is provided in the Cookie Policy.</p>
<h2>7. Data retention</h2><p>We retain personal information for as long as reasonably necessary to provide the service, maintain business and security records, satisfy contractual commitments, resolve disputes, and comply with legal obligations. Retention periods may vary by data type and customer agreement.</p>
<h2>8. Security</h2><p>We use administrative, technical, and organizational safeguards designed to protect information. No method of storage or transmission can be guaranteed to be completely secure, and customers should use appropriate access controls and credential practices.</p>
<h2>9. Privacy rights</h2><p>Depending on where you live and whether applicable legal thresholds are met, you may have rights to request access, correction, deletion, portability, restriction, or information about certain uses or disclosures of personal information. Where required by applicable law, we will provide a method to exercise applicable rights and will not discriminate against you for doing so.</p>
<h2>10. California disclosures</h2><p>California residents may have rights under applicable California privacy laws, including rights to know, correct, delete, and obtain information about certain disclosures, and rights relating to sale or sharing where those concepts apply. Emissa will honor legally applicable requests and recognized opt-out signals where required.</p>
<h2>11. International use</h2><p>If information is transferred across borders, Emissa will use legally appropriate transfer mechanisms where required by applicable law and contractual commitments.</p>
<h2>12. Children</h2><p>Emissa is a business service and is not directed to children. We do not knowingly seek personal information from children through the service.</p>
<h2>13. Changes</h2><p>We may update this Privacy Policy as the service, legal requirements, or data practices change. The effective date above will be updated when revisions are published.</p>
<h2>14. Contact</h2><p>Privacy questions and requests may be submitted through Emissa.tech's contact channels. Additional request mechanisms will be published when required for a particular jurisdiction.</p>
</LegalPage>}
