import type { Metadata } from 'next';
import { regulatoryCalendar } from '@/lib/seoExpansionPhase3';
import '../seo.css';

export const metadata:Metadata={title:'Supplier Compliance Regulatory Calendar',description:'Track selected supplier compliance milestones for CBAM, EUDR, battery passports, digital product passports and packaging EPR programs.',alternates:{canonical:'/regulatory-calendar'},keywords:['supplier compliance regulatory calendar','CBAM deadline','EUDR deadline','battery passport deadline','packaging EPR deadlines']};

export default function RegulatoryCalendarPage(){
  const schema={'@context':'https://schema.org','@type':'ItemList',name:'Emissa Supplier Compliance Regulatory Calendar',itemListElement:regulatoryCalendar.map((item,index)=>({'@type':'ListItem',position:index+1,name:item.title,url:`https://emissa.tech${item.href}`}))};
  return <main className="seoPage"><nav className="seoNav"><a className="seoBrand" href="/">EMISSA</a><div><a href="/regulations">Regulations</a><a href="/platform">Platform</a><a href="/tools">Tools</a><a href="/research">Research</a><a href="/demo">Demo</a></div></nav><header className="seoHero compact"><span className="seoKicker">Last reviewed • August 22, 2026</span><h1>Supplier Compliance Regulatory Calendar</h1><p>A maintained reference for selected milestones that can affect supplier, product, packaging and evidence workflows. Always verify current applicability against the linked official source.</p><div className="seoActions"><a className="seoPrimary" href="/demo">Book a private demo</a><a className="seoSecondary" href="/regulations">Browse regulatory intelligence</a></div></header><section className="seoGrid three">{regulatoryCalendar.map(item=><article className="seoCard" key={`${item.date}-${item.title}`}><span className="seoKicker">{item.status}</span><h2>{new Date(`${item.date}T12:00:00Z`).toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric',timeZone:'UTC'})}</h2><h3><a href={item.href}>{item.title}</a></h3><div className="seoActions"><a className="seoSecondary" href={item.source} target="_blank" rel="noreferrer">Official source ↗</a></div></article>)}</section><section className="seoSection"><span className="seoKicker">Operating model</span><h2>Turn dates into owned compliance work.</h2><p>A deadline is only useful when it is connected to the affected suppliers, products, evidence, responsible owners and approval steps. Emissa is designed to turn regulatory milestones into controlled obligations rather than calendar reminders with no underlying evidence state.</p></section><section className="seoCta"><h2>Map regulatory milestones to your supplier network.</h2><p>Build requirements, evidence dependencies, owners and review history around the regulations that affect your business.</p><a className="seoPrimary" href="/demo">See Emissa in action</a></section><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></main>;
}
